;;-*-coding: utf-8;-*-
(define-abbrev-table 'Rd-mode-abbrev-table
  '(
    ("`ag" "\\arguments" nil :count 0)
    ("`al" "\\alias" nil :count 0)
    ("`au" "\\author" nil :count 0)
    ("`bf" "\\bold" nil :count 0)
    ("`co" "\\code" nil :count 0)
    ("`de" "\\describe" nil :count 0)
    ("`dn" "\\description" nil :count 0)
    ("`dt" "\\details" nil :count 0)
    ("`em" "\\emph" nil :count 0)
    ("`en" "\\enumerate" nil :count 0)
    ("`ex" "\\examples" nil :count 0)
    ("`fi" "\\file" nil :count 0)
    ("`fo" "\\format" nil :count 0)
    ("`it" "\\item" nil :count 0)
    ("`iz" "\\itemize" nil :count 0)
    ("`kw" "\\keyword" nil :count 0)
    ("`li" "\\link" nil :count 0)
    ("`me" "\\method" nil :count 0)
    ("`na" "\\name" nil :count 0)
    ("`no" "\\note" nil :count 0)
    ("`re" "\\references" nil :count 0)
    ("`sa" "\\seealso" nil :count 0)
    ("`se" "\\section" nil :count 0)
    ("`so" "\\source" nil :count 0)
    ("`ss" "\\subsection" nil :count 0)
    ("`sy" "\\synopsis" nil :count 0)
    ("`ta" "\\tabular" nil :count 0)
    ("`ti" "\\title" nil :count 0)
    ("`us" "\\usage" nil :count 0)
    ("`va" "\\value" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("assisant" "assistant" nil :count 0)
    ("assistances" "assistance's" nil :count 1)
    ("developping" "developing" nil :count 1)
    ("particitation" "participation" nil :count 0)
    ("particuarly" "particularly" nil :count 2)
    ("prelimary" "preliminary" nil :count 0)
    ("primiarliy" "primarily" nil :count 0)
    ("questionairs" "questionnaires" nil :count 1)
    ("reseach" "research" nil :count 0)
    ("resillience" "resilience" nil :count 0)
    ("resilliences" "resilience's" nil :count 0)
    ("resrch" "research" nil :count 0)
    ("sigfnicant" "significant" nil :count 0)
    ("signifiant" "significant" nil :count 1)
    ("undergrate" "underrate" nil :count 0)
   ))

