;;-*-coding: utf-8;-*-
(define-abbrev-table 'Rd-mode-abbrev-table
  '(
    ("`ag" "\\arguments" nil :count 0)
    ("`al" "\\alias" nil :count 0)
    ("`au" "\\author" nil :count 0)
    ("`bf" "\\bold" nil :count 0)
    ("`co" "\\code" nil :count 0)
    ("`de" "\\describe" nil :count 0)
    ("`dn" "\\description" nil :count 0)
    ("`dt" "\\details" nil :count 0)
    ("`em" "\\emph" nil :count 0)
    ("`en" "\\enumerate" nil :count 0)
    ("`ex" "\\examples" nil :count 0)
    ("`fi" "\\file" nil :count 0)
    ("`fo" "\\format" nil :count 0)
    ("`it" "\\item" nil :count 0)
    ("`iz" "\\itemize" nil :count 0)
    ("`kw" "\\keyword" nil :count 0)
    ("`li" "\\link" nil :count 0)
    ("`me" "\\method" nil :count 0)
    ("`na" "\\name" nil :count 0)
    ("`no" "\\note" nil :count 0)
    ("`re" "\\references" nil :count 0)
    ("`sa" "\\seealso" nil :count 0)
    ("`se" "\\section" nil :count 0)
    ("`so" "\\source" nil :count 0)
    ("`ss" "\\subsection" nil :count 0)
    ("`sy" "\\synopsis" nil :count 0)
    ("`ta" "\\tabular" nil :count 0)
    ("`ti" "\\title" nil :count 0)
    ("`us" "\\usage" nil :count 0)
    ("`va" "\\value" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("acpabilities" "capabilities" nil :count 0)
    ("adantages" "advantages" nil :count 0)
    ("addresed" "addressed" nil :count 0)
    ("americal" "American" nil :count 0)
    ("analyais" "analysis" nil :count 0)
    ("analytics" "Analytics" nil :count 8)
    ("amidssion" "admission" nil :count 0)
    ("analyais" "analysis" nil :count 1)
    ("analytze" "analyze" nil :count 0)
    ("appliactions" "applications" nil :count 0)
    ("arthitecture" "architecture" nil :count 0)
    ("assement" "easement" nil :count 0)
    ("assisant" "assistant" nil :count 1)
    ("assistances" "assistance's" nil :count 1)
    ("assistantship" "assistant-ship" nil :count 0)
    ("assitant" "assistant" nil :count 0)
    ("assocaited" "associated" nil :count 0)
    ("asssess" "assess" nil :count 0)
    ("atmosperhic" "atmospheric" nil :count 0)
    ("avaiable" "available" nil :count 0)
    ("avaialble" "available" nil :count 0)
<<<<<<< HEAD
    ("avaible" "affable" nil :count 0)
    ("availalle" "available" nil :count 0)
    ("cargographic" "Cartographic" nil :count 0)
    ("communites" "communities" nil :count 1)
    ("continure" "Continue" nil :count 0)
    ("coperation" "cooperation" nil :count 0)
    ("curricuculum" "curriculum" nil :count 0)
    ("cyberinfrastructure" "cyberinfrastrure" nil :count 0)
    ("develope" "Developer" nil :count 2)
    ("developping" "developing" nil :count 1)
    ("devicens" "devices" nil :count 0)
    ("dicussion" "discussion" nil :count 0)
    ("diffrence" "difference" nil :count 0)
    ("diffrent" "different" nil :count 0)
    ("dificuult" "difficult" nil :count 0)
=======
    ("candidiate" "candidate" nil :count 0)
    ("charact" "character" nil :count 1)
    ("coastoal" "coastal" nil :count 0)
    ("collabration" "collaboration" nil :count 0)
    ("communites" "communities" nil :count 0)
    ("componenets" "components" nil :count 0)
    ("continure" "Continue" nil :count 0)
    ("cyberinfrastructure" "cyberinfrastrure" nil :count 1)
    ("datasets" "data sets" nil :count 1)
    ("demonstarte" "demonstrate" nil :count 0)
    ("demonstreated" "demonstrated" nil :count 0)
    ("develope" "Developer" nil :count 0)
    ("developping" "developing" nil :count 1)
    ("diaster" "disaster" nil :count 1)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("dimentional" "dimensional" nil :count 0)
    ("dissminate" "disseminate" nil :count 0)
    ("dissseimiat" "disseminate" nil :count 0)
    ("disssmination" "Dissemination" nil :count 0)
<<<<<<< HEAD
    ("disucssion" "discussion" nil :count 0)
    ("divices" "devices" nil :count 0)
    ("emmpahsized" "emphasized" nil :count 0)
=======
    ("distince" "distance" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("environemtnal" "Environmental" nil :count 0)
    ("envrionemntal" "environmental" nil :count 0)
    ("envrionemtnl" "environmental" nil :count 0)
    ("epidemological" "epidemiological" nil :count 0)
    ("esri" "ESR" nil :count 2)
    ("estabilish" "Establish" nil :count 0)
<<<<<<< HEAD
    ("expertises" "expertise's" nil :count 0)
    ("fragementation" "fragmentation" nil :count 0)
    ("genearted" "generated" nil :count 0)
    ("geortia" "Georgia" nil :count 0)
    ("graduat" "graduate" nil :count 0)
    ("hetergeneous" "heterogeneous" nil :count 1)
    ("idigeneous" "indigenous" nil :count 0)
    ("impactful" "impact" nil :count 8)
    ("imporant" "important" nil :count 0)
    ("infrastucture" "infrastructure" nil :count 0)
    ("insigtuful" "insightful" nil :count 0)
    ("intereseted" "interested" nil :count 0)
    ("intergration" "integration" nil :count 0)
    ("justitic" "static" nil :count 0)
    ("levareage" "Leverage" nil :count 0)
    ("literaure" "literature" nil :count 1)
=======
    ("estimste" "estimate" nil :count 0)
    ("generlized" "generalized" nil :count 0)
    ("geortia" "Georgia" nil :count 0)
    ("graduat" "graduate" nil :count 0)
    ("hetergeneous" "heterogeneous" nil :count 1)
    ("innovalty" "novelty" nil :count 0)
    ("innovaty" "innovate" nil :count 0)
    ("intereseted" "interested" nil :count 0)
    ("intergration" "integration" nil :count 0)
    ("justiied" "justified" nil :count 0)
    ("longitudue" "longitudinal" nil :count 0)
    ("managment" "management" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("materails" "materials" nil :count 0)
    ("mentorship" "mentor ship" nil :count 0)
    ("metho" "method" nil :count 1)
    ("methodd" "methods" nil :count 0)
<<<<<<< HEAD
    ("methodologicla" "methodological" nil :count 0)
=======
    ("methododlogy" "methodology" nil :count 0)
    ("methodogical" "methodical" nil :count 0)
    ("methodoligcal" "methodological" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("metodology" "methodology" nil :count 0)
    ("metropolitial" "metropolitan" nil :count 0)
    ("modelign" "modeling" nil :count 1)
    ("mystory" "mystery" nil :count 0)
    ("occissionally" "occasionally" nil :count 0)
    ("pacakge" "package" nil :count 0)
    ("parametetric" "parametric" nil :count 0)
    ("paremeter" "parameter" nil :count 0)
    ("parimary" "primary" nil :count 0)
    ("particitation" "participation" nil :count 0)
<<<<<<< HEAD
    ("particuarly" "particularly" nil :count 5)
=======
    ("particuarly" "particularly" nil :count 3)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("particulaly" "particularly" nil :count 0)
    ("percpetions" "perceptions" nil :count 0)
    ("postdoctorial" "postdoctoral" nil :count 0)
    ("practioners" "practitioners" nil :count 0)
    ("pregenant" "pregnant" nil :count 0)
    ("prelimary" "preliminary" nil :count 0)
    ("prelimiary" "preliminary" nil :count 1)
    ("primarliy" "primarily" nil :count 0)
    ("primiarliy" "primarily" nil :count 0)
<<<<<<< HEAD
    ("primiarly" "primarily" nil :count 0)
    ("propsoal" "proposal" nil :count 0)
=======
    ("propation" "propagation" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("protoype" "prototype" nil :count 1)
    ("pursvasive" "persuasive" nil :count 0)
    ("questionairs" "questionnaires" nil :count 1)
    ("recuited" "recruited" nil :count 0)
<<<<<<< HEAD
    ("reproducibility" "reproducible" nil :count 0)
=======
    ("reocords" "records" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
    ("reseach" "research" nil :count 0)
    ("reseracher" "researcher" nil :count 0)
    ("resillience" "resilience" nil :count 0)
    ("resilliences" "resilience's" nil :count 0)
    ("resrch" "research" nil :count 0)
    ("restricutions" "restrictions" nil :count 0)
    ("shou" "shout" nil :count 1)
    ("sigfnicant" "significant" nil :count 0)
    ("signifiant" "significant" nil :count 1)
    ("statsitical" "statistical" nil :count 0)
    ("strenghts" "Strengths" nil :count 1)
    ("strucutre" "structure" nil :count 0)
    ("techinique" "technique" nil :count 0)
    ("technilogies" "technologies" nil :count 0)
    ("technoical" "technical" nil :count 0)
    ("transferrable" "transferable" nil :count 0)
    ("tricyrides" "traceries" nil :count 0)
    ("ubiquitious" "ubiquitous" nil :count 0)
    ("undergrate" "underrate" nil :count 0)
    ("univeristy" "University" nil :count 0)
<<<<<<< HEAD
    ("wearble" "wearable" nil :count 0)
    ("workspaces" "workspace" nil :count 1)
=======
    ("univresity" "University" nil :count 0)
>>>>>>> c2149a979f55e6dda43b755f2f88a94f22868a7a
   ))

