;;-*-coding: utf-8;-*-
(define-abbrev-table 'Buffer-menu-mode-abbrev-table '())

(define-abbrev-table 'Custom-mode-abbrev-table '())

(define-abbrev-table 'Info-edit-mode-abbrev-table '())

(define-abbrev-table 'Man-mode-abbrev-table '())

(define-abbrev-table 'Rd-mode-abbrev-table
  '(
    ("`ag" "\\arguments" nil 0)
    ("`al" "\\alias" nil 0)
    ("`au" "\\author" nil 0)
    ("`bf" "\\bold" nil 0)
    ("`co" "\\code" nil 0)
    ("`de" "\\describe" nil 0)
    ("`dn" "\\description" nil 0)
    ("`dt" "\\details" nil 0)
    ("`em" "\\emph" nil 0)
    ("`en" "\\enumerate" nil 0)
    ("`ex" "\\examples" nil 0)
    ("`fi" "\\file" nil 0)
    ("`fo" "\\format" nil 0)
    ("`it" "\\item" nil 0)
    ("`iz" "\\itemize" nil 0)
    ("`kw" "\\keyword" nil 0)
    ("`li" "\\link" nil 0)
    ("`me" "\\method" nil 0)
    ("`na" "\\name" nil 0)
    ("`no" "\\note" nil 0)
    ("`re" "\\references" nil 0)
    ("`sa" "\\seealso" nil 0)
    ("`se" "\\section" nil 0)
    ("`so" "\\source" nil 0)
    ("`ss" "\\subsection" nil 0)
    ("`sy" "\\synopsis" nil 0)
    ("`ta" "\\tabular" nil 0)
    ("`ti" "\\title" nil 0)
    ("`us" "\\usage" nil 0)
    ("`va" "\\value" nil 0)
   ))

(define-abbrev-table 'S+-transcript-mode-abbrev-table '())

(define-abbrev-table 'SAS-listing-mode-abbrev-table '())

(define-abbrev-table 'SAS-log-mode-abbrev-table '())

(define-abbrev-table 'SAS-mode-abbrev-table '())

(define-abbrev-table 'TeX-error-overview-mode-abbrev-table '())

(define-abbrev-table 'TeX-output-mode-abbrev-table '())

(define-abbrev-table 'TeX-special-mode-abbrev-table '())

(define-abbrev-table 'anaconda-mode-view-mode-abbrev-table '())

(define-abbrev-table 'awk-mode-abbrev-table '())

(define-abbrev-table 'biblio-selection-mode-abbrev-table '())

(define-abbrev-table 'bibtex-mode-abbrev-table '())

(define-abbrev-table 'bookmark-bmenu-mode-abbrev-table '())

(define-abbrev-table 'bookmark-edit-annotation-mode-abbrev-table '())

(define-abbrev-table 'bsh-script-mode-abbrev-table '())

(define-abbrev-table 'c++-mode-abbrev-table '())

(define-abbrev-table 'c-mode-abbrev-table '())

(define-abbrev-table 'calc-trail-mode-abbrev-table '())

(define-abbrev-table 'calendar-mode-abbrev-table '())

(define-abbrev-table 'change-log-mode-abbrev-table '())

(define-abbrev-table 'comint-mode-abbrev-table '())

(define-abbrev-table 'completion-list-mode-abbrev-table '())

(define-abbrev-table 'conf-colon-mode-abbrev-table '())

(define-abbrev-table 'conf-javaprop-mode-abbrev-table '())

(define-abbrev-table 'conf-ppd-mode-abbrev-table '())

(define-abbrev-table 'conf-space-mode-abbrev-table '())

(define-abbrev-table 'conf-unix-mode-abbrev-table '())

(define-abbrev-table 'conf-windows-mode-abbrev-table '())

(define-abbrev-table 'conf-xdefaults-mode-abbrev-table '())

(define-abbrev-table 'css-mode-abbrev-table '())

(define-abbrev-table 'data-debug-mode-abbrev-table '())

(define-abbrev-table 'debugger-mode-abbrev-table '())

(define-abbrev-table 'diary-fancy-display-mode-abbrev-table '())

(define-abbrev-table 'diary-mode-abbrev-table '())

(define-abbrev-table 'diff-mode-abbrev-table '())

(define-abbrev-table 'dig-mode-abbrev-table '())

(define-abbrev-table 'display-time-world-mode-abbrev-table '())

(define-abbrev-table 'doctex-mode-abbrev-table '())

(define-abbrev-table 'edebug-eval-mode-abbrev-table '())

(define-abbrev-table 'edit-abbrevs-mode-abbrev-table '())

(define-abbrev-table 'eieio-custom-mode-abbrev-table '())

(define-abbrev-table 'elisp-byte-code-mode-abbrev-table '())

(define-abbrev-table 'elpy-refactor-mode-abbrev-table '())

(define-abbrev-table 'emacs-lisp-mode-abbrev-table '())

(define-abbrev-table 'emms-lyrics-mode-abbrev-table '())

(define-abbrev-table 'emms-show-all-mode-abbrev-table '())

(define-abbrev-table 'emms-tag-editor-mode-abbrev-table '())

(define-abbrev-table 'epa-info-mode-abbrev-table '())

(define-abbrev-table 'epa-key-list-mode-abbrev-table '())

(define-abbrev-table 'epa-key-mode-abbrev-table '())

(define-abbrev-table 'ert-results-mode-abbrev-table '())

(define-abbrev-table 'ert-simple-view-mode-abbrev-table '())

(define-abbrev-table 'eshell-mode-abbrev-table '())

(define-abbrev-table 'ess-bugs-mode-abbrev-table '())

(define-abbrev-table 'ess-help-mode-abbrev-table '())

(define-abbrev-table 'ess-jags-mode-abbrev-table '())

(define-abbrev-table 'ess-julia-help-mode-abbrev-table '())

(define-abbrev-table 'ess-julia-mode-abbrev-table '())

(define-abbrev-table 'ess-mode-abbrev-table '())

(define-abbrev-table 'ess-r-help-mode-abbrev-table '())

(define-abbrev-table 'ess-r-mode-abbrev-table '())

(define-abbrev-table 'ess-r-transcript-mode-abbrev-table '())

(define-abbrev-table 'ess-stata-help-mode-abbrev-table '())

(define-abbrev-table 'ess-stata-mode-abbrev-table '())

(define-abbrev-table 'ess-stata-transcript-mode-abbrev-table '())

(define-abbrev-table 'ess-transcript-mode-abbrev-table '())

(define-abbrev-table 'ess-watch-mode-abbrev-table '())

(define-abbrev-table 'evil-command-window-mode-abbrev-table '())

(define-abbrev-table 'evil-list-view-mode-abbrev-table '())

(define-abbrev-table 'eww-bookmark-mode-abbrev-table '())

(define-abbrev-table 'eww-buffers-mode-abbrev-table '())

(define-abbrev-table 'eww-history-mode-abbrev-table '())

(define-abbrev-table 'eww-mode-abbrev-table '())

(define-abbrev-table 'ffip-diff-mode-abbrev-table '())

(define-abbrev-table 'flycheck-error-list-mode-abbrev-table '())

(define-abbrev-table 'flycheck-error-message-mode-abbrev-table '())

(define-abbrev-table 'flycheck-explain-error-mode-abbrev-table '())

(define-abbrev-table 'flycheck-verify-mode-abbrev-table '())

(define-abbrev-table 'flymake-diagnostics-buffer-mode-abbrev-table '())

(define-abbrev-table 'fundamental-mode-abbrev-table '())

(define-abbrev-table 'gdb-script-mode-abbrev-table '())

(define-abbrev-table 'gfm-mode-abbrev-table '())

(define-abbrev-table 'gfm-view-mode-abbrev-table '())

(define-abbrev-table 'ggtags-global-mode-abbrev-table '())

(define-abbrev-table 'ggtags-view-search-history-mode-abbrev-table '())

(define-abbrev-table 'git-commit-elisp-text-mode-abbrev-table '())

(define-abbrev-table 'global-abbrev-table
  '(
    ("abbout" "about" nil 0)
    ("abotu" "about" nil 0)
    ("abouta" "about a" nil 0)
    ("aboutit" "about it" nil 0)
    ("aboutthe" "about the" nil 0)
    ("abscence" "absence" nil 0)
    ("accesories" "accessories" nil 0)
    ("accidant" "accident" nil 0)
    ("accomodate" "accommodate" nil 0)
    ("accordingto" "according to" nil 0)
    ("accross" "across" nil 0)
    ("acheive" "achieve" nil 0)
    ("acheived" "achieved" nil 0)
    ("acheiving" "achieving" nil 0)
    ("acn" "can" nil 0)
    ("acommodate" "accommodate" nil 0)
    ("acomodate" "accommodate" nil 0)
    ("acomplished" "accomplished" nil 0)
    ("actualyl" "actually" nil 0)
    ("acurate" "accurate" nil 0)
    ("addictional" "additional" nil 0)
    ("additinal" "additional" nil 0)
    ("addtional" "additional" nil 0)
    ("addtions" "additions" nil 0)
    ("adequit" "adequate" nil 0)
    ("adequite" "adequate" nil 0)
    ("adn" "and" nil 0)
    ("advanage" "advantage" nil 0)
    ("affraid" "afraid" nil 0)
    ("afterthe" "after the" nil 0)
    ("aganist" "against" nil 0)
    ("aggresive" "aggressive" nil 0)
    ("agian" "again" nil 0)
    ("agreemeent" "agreement" nil 0)
    ("agreemeents" "agreements" nil 0)
    ("agreemnet" "agreement" nil 0)
    ("agreemnets" "agreements" nil 0)
    ("agressive" "aggressive" nil 0)
    ("ahppen" "happen" nil 0)
    ("ahve" "have" nil 1)
    ("allwasy" "always" nil 0)
    ("allwyas" "always" nil 0)
    ("almots" "almost" nil 0)
    ("almsot" "almost" nil 0)
    ("alomst" "almost" nil 0)
    ("alot" "a lot" nil 0)
    ("alraedy" "already" nil 0)
    ("alreayd" "already" nil 0)
    ("alreday" "already" nil 0)
    ("alwasy" "always" nil 1)
    ("alwats" "always" nil 0)
    ("alway" "always" nil 0)
    ("alwyas" "always" nil 0)
    ("amde" "made" nil 0)
    ("ameria" "America" nil 0)
    ("amke" "make" nil 0)
    ("amkes" "makes" nil 0)
    ("anbd" "and" nil 0)
    ("andone" "and one" nil 0)
    ("andt he" "and the" nil 0)
    ("andteh" "and the" nil 0)
    ("andthe" "and the" nil 0)
    ("anothe" "another" nil 0)
    ("anual" "annual" nil 0)
    ("apache" "Apache" nil 4)
    ("apparant" "apparent" nil 0)
    ("apparrent" "apparent" nil 0)
    ("appearence" "appearance" nil 0)
    ("appeares" "appears" nil 0)
    ("applicaiton" "application" nil 0)
    ("applicaitons" "applications" nil 0)
    ("applyed" "applied" nil 0)
    ("appointiment" "appointment" nil 0)
    ("approrpiate" "appropriate" nil 0)
    ("approrpriate" "appropriate" nil 0)
    ("aquisition" "acquisition" nil 0)
    ("aquisitions" "acquisitions" nil 0)
    ("arent" "aren't" nil 0)
    ("arguement" "argument" nil 0)
    ("arguements" "arguments" nil 0)
    ("arnt" "aren't" nil 0)
    ("arond" "around" nil 0)
    ("artical" "article" nil 0)
    ("articel" "article" nil 0)
    ("asdvertising" "advertising" nil 0)
    ("assistent" "assistant" nil 0)
    ("asthe" "as the" nil 0)
    ("atention" "attention" nil 0)
    ("atmospher" "atmosphere" nil 1)
    ("attentioin" "attention" nil 0)
    ("atthe" "at the" nil 0)
    ("audeince" "audience" nil 0)
    ("audiance" "audience" nil 0)
    ("authetication" "authentication" nil 0)
    ("availalbe" "available" nil 0)
    ("awya" "away" nil 0)
    ("aywa" "away" nil 0)
    ("bakc" "back" nil 0)
    ("balence" "balance" nil 0)
    ("ballance" "balance" nil 0)
    ("baout" "about" nil 0)
    ("bcak" "back" nil 0)
    ("beacause" "because" nil 1)
    ("beacuse" "because" nil 0)
    ("becasue" "because" nil 0)
    ("becaus" "because" nil 0)
    ("becausea" "because a" nil 0)
    ("becauseof" "because of" nil 0)
    ("becausethe" "because the" nil 0)
    ("becauseyou" "because you" nil 0)
    ("becomeing" "becoming" nil 0)
    ("becomming" "becoming" nil 0)
    ("becuase" "because" nil 0)
    ("becuse" "because" nil 0)
    ("befoer" "before" nil 0)
    ("beggining" "beginning" nil 0)
    ("begining" "beginning" nil 0)
    ("beginining" "beginning" nil 0)
    ("behabviour" "behaviour" nil 0)
    ("behaivior" "behaviour" nil 0)
    ("behavour" "behaviour" nil 0)
    ("beleiev" "believe" nil 0)
    ("beleieve" "believe" nil 0)
    ("beleif" "belief" nil 0)
    ("beleive" "believe" nil 0)
    ("beleived" "believed" nil 0)
    ("beleives" "believes" nil 0)
    ("beliefe" "belief" nil 0)
    ("beliveve" "believe" nil 0)
    ("benifit" "benefit" nil 0)
    ("benifits" "benefits" nil 0)
    ("betwen" "between" nil 0)
    ("beutiful" "beautiful" nil 0)
    ("blase" "blase" nil 0)
    ("boxs" "boxes" nil 0)
    ("brodcast" "broadcast" nil 0)
    ("butthe" "but the" nil 0)
    ("bve" "be" nil 0)
    ("cafe" "cafe" nil 0)
    ("caharcter" "character" nil 0)
    ("calcullated" "calculated" nil 0)
    ("calulated" "calculated" nil 0)
    ("candidtae" "candidate" nil 0)
    ("candidtaes" "candidates" nil 0)
    ("caontains" "contains" nil 0)
    ("capabilites" "capabilities" nil 0)
    ("catagory" "category" nil 0)
    ("categiory" "category" nil 0)
    ("certian" "certain" nil 0)
    ("challange" "challenge" nil 0)
    ("challanges" "challenges" nil 0)
    ("chaneg" "change" nil 0)
    ("chanegs" "changes" nil 0)
    ("changable" "changeable" nil 0)
    ("changeing" "changing" nil 0)
    ("changng" "changing" nil 0)
    ("charachter" "character" nil 0)
    ("charachters" "characters" nil 0)
    ("charactor" "character" nil 0)
    ("charecter" "character" nil 0)
    ("charector" "character" nil 0)
    ("cheif" "chief" nil 0)
    ("chekc" "check" nil 0)
    ("chnage" "change" nil 0)
    ("cieling" "ceiling" nil 0)
    ("circut" "circuit" nil 0)
    ("claer" "clear" nil 0)
    ("claered" "cleared" nil 0)
    ("claerly" "clearly" nil 0)
    ("cliant" "client" nil 0)
    ("cliche" "cliche" nil 0)
    ("cna" "can" nil 0)
    ("colection" "collection" nil 0)
    ("comanies" "companies" nil 0)
    ("comany" "company" nil 0)
    ("comapnies" "companies" nil 0)
    ("comapny" "company" nil 0)
    ("combintation" "combination" nil 0)
    ("comited" "committed" nil 0)
    ("comittee" "committee" nil 0)
    ("commadn" "command" nil 0)
    ("comming" "coming" nil 0)
    ("commitee" "committee" nil 0)
    ("committe" "committee" nil 1)
    ("committment" "commitment" nil 0)
    ("committments" "commitments" nil 0)
    ("committy" "committee" nil 0)
    ("comntain" "contain" nil 0)
    ("comntains" "contains" nil 0)
    ("compair" "compare" nil 0)
    ("compatable" "compatible" nil 0)
    ("compleated" "completed" nil 0)
    ("compleatly" "completely" nil 0)
    ("compleatness" "completeness" nil 0)
    ("completly" "completely" nil 0)
    ("completness" "completeness" nil 0)
    ("complteted" "completed" nil 0)
    ("composate" "composite" nil 0)
    ("compteted" "completed" nil 0)
    ("comtain" "contain" nil 0)
    ("comtains" "contains" nil 0)
    ("comunicate" "communicate" nil 0)
    ("comunity" "community" nil 0)
    ("condersider" "consider" nil 0)
    ("condolances" "condolences" nil 0)
    ("conected" "connected" nil 0)
    ("conferance" "conference" nil 0)
    ("configration" "configuration" nil 0)
    ("confirmmation" "confirmation" nil 0)
    ("conjuntion" "conjunction" nil 0)
    ("considerit" "considerate" nil 0)
    ("considerite" "considerate" nil 0)
    ("consistant" "consistent" nil 0)
    ("consonent" "consonant" nil 0)
    ("conspiricy" "conspiracy" nil 0)
    ("constuction" "construction" nil 0)
    ("consultent" "consultant" nil 0)
    ("consumeable" "consumable" nil 0)
    ("contitions" "conditions" nil 0)
    ("controlable" "controllable" nil 0)
    ("convertable" "convertible" nil 0)
    ("cooparate" "cooperate" nil 0)
    ("cooporate" "cooperate" nil 0)
    ("corproation" "corporation" nil 0)
    ("corproations" "corporations" nil 0)
    ("corrospond" "correspond" nil 0)
    ("corruptable" "corruptible" nil 0)
    ("cotten" "cotton" nil 0)
    ("coudl" "could" nil 0)
    ("coudln" "couldn" nil 0)
    ("coudn" "couldn" nil 0)
    ("couldnt" "couldn't" nil 0)
    ("couldthe" "could the" nil 0)
    ("cpoy" "copy" nil 0)
    ("creme" "creme" nil 0)
    ("ctaegory" "category" nil 0)
    ("cusotmer" "customer" nil 0)
    ("cusotmers" "customers" nil 0)
    ("cutsomer" "customer" nil 0)
    ("cutsomers" "customers" nil 0)
    ("cxan" "can" nil 0)
    ("danceing" "dancing" nil 0)
    ("dcument" "document" nil 0)
    ("deatils" "details" nil 0)
    ("decison" "decision" nil 0)
    ("decisons" "decisions" nil 0)
    ("decor" "decor" nil 0)
    ("defendent" "defendant" nil 0)
    ("definately" "definitely" nil 0)
    ("definded" "defined" nil 0)
    ("dependances" "dependencies" nil 0)
    ("deptartment" "department" nil 0)
    ("desicion" "decision" nil 0)
    ("desicions" "decisions" nil 0)
    ("desision" "decision" nil 0)
    ("desisions" "decisions" nil 0)
    ("detente" "detente" nil 0)
    ("determin" "determine" nil 0)
    ("determins" "determine" nil 0)
    ("develeoprs" "developers" nil 0)
    ("devellop" "develop" nil 0)
    ("develloped" "developed" nil 0)
    ("develloper" "developer" nil 0)
    ("devellopers" "developers" nil 0)
    ("develloping" "developing" nil 0)
    ("devellopment" "development" nil 0)
    ("devellopments" "developments" nil 0)
    ("devellops" "develop" nil 0)
    ("develope" "develop" nil 3)
    ("developement" "development" nil 0)
    ("developements" "developments" nil 0)
    ("developor" "developer" nil 0)
    ("developors" "developers" nil 0)
    ("develpment" "development" nil 0)
    ("devloped" "developed" nil 0)
    ("diaplay" "display" nil 0)
    ("didint" "didn't" nil 0)
    ("didnot" "did not" nil 0)
    ("didnt" "didn't" nil 0)
    ("difefrent" "different" nil 0)
    ("diferences" "differences" nil 0)
    ("differance" "difference" nil 0)
    ("differances" "differences" nil 0)
    ("differant" "different" nil 0)
    ("differemt" "different" nil 0)
    ("differnt" "different" nil 3)
    ("diffrent" "different" nil 0)
    ("directer" "director" nil 0)
    ("directers" "directors" nil 0)
    ("directiosn" "direction" nil 0)
    ("disatisfied" "dissatisfied" nil 0)
    ("discoverd" "discovered" nil 0)
    ("disign" "design" nil 0)
    ("dispaly" "display" nil 0)
    ("dissonent" "dissonant" nil 0)
    ("distribusion" "distribution" nil 0)
    ("distrubution" "distribution" nil 0)
    ("divsion" "division" nil 0)
    ("docuement" "documents" nil 0)
    ("docuemnt" "document" nil 0)
    ("documetn" "document" nil 0)
    ("documnet" "document" nil 0)
    ("documnets" "documents" nil 0)
    ("doese" "does" nil 0)
    ("doesnt" "doesn't" nil 0)
    ("doign" "doing" nil 0)
    ("doimg" "doing" nil 0)
    ("doind" "doing" nil 0)
    ("dollers" "dollars" nil 0)
    ("donig" "doing" nil 0)
    ("dont" "don't" nil 0)
    ("dosnt" "doesn't" nil 0)
    ("driveing" "driving" nil 0)
    ("drnik" "drink" nil 0)
    ("eclair" "eclair" nil 0)
    ("efel" "feel" nil 0)
    ("effecient" "efficient" nil 0)
    ("efort" "effort" nil 0)
    ("eforts" "efforts" nil 0)
    ("ehr" "her" nil 0)
    ("eligable" "eligible" nil 0)
    ("emacs" "Emacs" nil 1)
    ("embarass" "embarrass" nil 0)
    ("emigre" "emigre" nil 0)
    ("enahancements" "enhancements" nil 0)
    ("english" "English" nil 2)
    ("enought" "enough" nil 0)
    ("entree" "entree" nil 0)
    ("equippment" "equipment" nil 0)
    ("equivalant" "equivalent" nil 0)
    ("esle" "else" nil 0)
    ("especally" "especially" nil 0)
    ("especialyl" "especially" nil 0)
    ("espesially" "especially" nil 0)
    ("excellant" "excellent" nil 0)
    ("excercise" "exercise" nil 0)
    ("exchagne" "exchange" nil 0)
    ("exchagnes" "exchanges" nil 0)
    ("excitment" "excitement" nil 0)
    ("exhcange" "exchange" nil 0)
    ("exhcanges" "exchanges" nil 0)
    ("experiance" "experience" nil 0)
    ("experienc" "experience" nil 0)
    ("exprience" "experience" nil 0)
    ("exprienced" "experienced" nil 0)
    ("eyt" "yet" nil 0)
    ("facade" "facade" nil 0)
    ("faeture" "feature" nil 0)
    ("faetures" "features" nil 0)
    ("familair" "familiar" nil 0)
    ("familar" "familiar" nil 1)
    ("familliar" "familiar" nil 0)
    ("fammiliar" "familiar" nil 0)
    ("feild" "field" nil 0)
    ("feilds" "fields" nil 0)
    ("fianlly" "finally" nil 0)
    ("fidn" "find" nil 0)
    ("fifith" "fifth" nil 0)
    ("finalyl" "finally" nil 0)
    ("finnally" "finally" nil 0)
    ("finnish" "finish" nil 0)
    ("firends" "friends" nil 0)
    ("firts" "first" nil 0)
    ("fixit" "fix it" nil 0)
    ("follwo" "follow" nil 0)
    ("follwoing" "following" nil 0)
    ("foloowing" "following" nil 0)
    ("fora" "for a" nil 0)
    ("foriegn" "foreign" nil 0)
    ("forthe" "for the" nil 2)
    ("forwrd" "forward" nil 0)
    ("forwrds" "forwards" nil 0)
    ("foudn" "found" nil 0)
    ("foward" "forward" nil 0)
    ("fowards" "forwards" nil 0)
    ("freind" "friend" nil 0)
    ("freindly" "friendly" nil 0)
    ("freinds" "friends" nil 0)
    ("frmo" "from" nil 0)
    ("fromt he" "from the" nil 0)
    ("fromthe" "from the" nil 0)
    ("furneral" "funeral" nil 0)
    ("fwe" "few" nil 0)
    ("garantee" "guarantee" nil 0)
    ("gaurd" "guard" nil 0)
    ("gemeral" "general" nil 0)
    ("gerat" "great" nil 0)
    ("gerneral" "general" nil 0)
    ("geting" "getting" nil 0)
    ("gettin" "getting" nil 0)
    ("gievn" "given" nil 0)
    ("giveing" "giving" nil 0)
    ("gloabl" "global" nil 0)
    ("goign" "going" nil 0)
    ("gonig" "going" nil 0)
    ("govenment" "government" nil 0)
    ("goverment" "government" nil 1)
    ("gruop" "group" nil 0)
    ("gruops" "groups" nil 0)
    ("grwo" "grow" nil 0)
    ("guidlines" "guidelines" nil 0)
    ("hadbeen" "had been" nil 0)
    ("hadnt" "hadn't" nil 0)
    ("haev" "have" nil 0)
    ("hapen" "happen" nil 0)
    ("hapened" "happened" nil 0)
    ("hapening" "happening" nil 0)
    ("hapens" "happens" nil 0)
    ("happend" "happened" nil 1)
    ("hasbeen" "has been" nil 0)
    ("hasnt" "hasn't" nil 0)
    ("havebeen" "have been" nil 0)
    ("haveing" "having" nil 0)
    ("haven;t" "haven't" nil 0)
    ("hda" "had" nil 0)
    ("hearign" "hearing" nil 0)
    ("heire" "he-ire" nil 0)
    ("helpdesk" "help-desk" nil 0)
    ("helpfull" "helpful" nil 0)
    ("herat" "heart" nil 0)
    ("hesaid" "he said" nil 0)
    ("hewas" "he was" nil 0)
    ("hge" "he" nil 0)
    ("hier" "heir" nil 0)
    ("hismelf" "himself" nil 0)
    ("hiten" "hitting" nil 0)
    ("hitten" "hitting" nil 0)
    ("hlep" "help" nil 0)
    ("howerver" "however" nil 0)
    ("hsa" "has" nil 0)
    ("hsi" "his" nil 0)
    ("hte" "the" nil 18)
    ("htere" "there" nil 0)
    ("htese" "these" nil 0)
    ("htey" "they" nil 0)
    ("hting" "thing" nil 0)
    ("htink" "think" nil 0)
    ("htis" "this" nil 0)
    ("htp:" "http:" nil 0)
    ("http:\\\\" "http:// class=" string 0)
    ("httpL" "http: class=" string 0)
    ("hvae" "have" nil 0)
    ("hvaing" "having" nil 0)
    ("hwich" "which" nil 0)
    ("i" "I" nil 315)
    ("idae" "idea" nil 0)
    ("idaes" "ideas" nil 0)
    ("identifiy" "identify" nil 0)
    ("identofy" "identify" nil 0)
    ("ihs" "his" nil 0)
    ("imediate" "immediate" nil 3)
    ("imediatly" "immediately" nil 0)
    ("immediatly" "immediately" nil 0)
    ("impilies" "implies" nil 0)
    ("implemenation" "implementation" nil 0)
    ("importent" "important" nil 0)
    ("importnat" "important" nil 0)
    ("impossable" "impossible" nil 0)
    ("improvemnt" "improvement" nil 1)
    ("improvment" "improvement" nil 1)
    ("includ" "include" nil 1)
    ("indecate" "indicate" nil 0)
    ("indenpendence" "independence" nil 0)
    ("indenpendent" "independent" nil 0)
    ("indepedent" "independent" nil 0)
    ("independance" "independence" nil 0)
    ("independant" "independent" nil 0)
    ("influance" "influence" nil 0)
    ("infomation" "information" nil 0)
    ("informatoin" "information" nil 0)
    ("inital" "initial" nil 0)
    ("initalization" "initialization" nil 0)
    ("instaleld" "installed" nil 0)
    ("insted" "instead" nil 0)
    ("insurence" "insurance" nil 0)
    ("inteh" "in the" nil 0)
    ("interum" "interim" nil 0)
    ("inthe" "in the" nil 2)
    ("inturn" "in turn" nil 0)
    ("invitaion" "invitation" nil 0)
    ("invstigated" "investigated" nil 0)
    ("inwhich" "in which" nil 0)
    ("isnt" "isn't" nil 0)
    ("isthe" "is the" nil 0)
    ("itis" "it is" nil 1)
    ("ititial" "initial" nil 0)
    ("itll" "it'll" nil 0)
    ("itnerest" "interest" nil 0)
    ("itnerested" "interested" nil 0)
    ("itneresting" "interesting" nil 0)
    ("itnerests" "interests" nil 0)
    ("itwas" "it was" nil 0)
    ("ivestigative" "investigative" nil 0)
    ("iwll" "will" nil 0)
    ("iwth" "with" nil 0)
    ("jsut" "just" nil 0)
    ("jugment" "judgment" nil 0)
    ("knowldge" "knowledge" nil 0)
    ("knowlege" "knowledge" nil 0)
    ("knwo" "know" nil 0)
    ("knwon" "known" nil 0)
    ("knwos" "knows" nil 0)
    ("konw" "know" nil 0)
    ("konwn" "known" nil 0)
    ("konws" "knows" nil 0)
    ("labratory" "laboratory" nil 0)
    ("languange" "language" nil 0)
    ("lastyear" "last year" nil 0)
    ("learnign" "learning" nil 1)
    ("lenght" "length" nil 0)
    ("levle" "level" nil 0)
    ("libary" "library" nil 0)
    ("librarry" "library" nil 0)
    ("librery" "library" nil 0)
    ("liek" "like" nil 0)
    ("liekd" "liked" nil 0)
    ("lieutenent" "lieutenant" nil 0)
    ("liev" "live" nil 0)
    ("likly" "likely" nil 0)
    ("lisense" "license" nil 0)
    ("littel" "little" nil 0)
    ("litttle" "little" nil 0)
    ("liuke" "like" nil 0)
    ("liveing" "living" nil 0)
    ("loev" "love" nil 0)
    ("lonly" "lonely" nil 0)
    ("lookign" "looking" nil 0)
    ("lookup" "look up" nil 0)
    ("maintenence" "maintenance" nil 0)
    ("makeing" "making" nil 0)
    ("managment" "management" nil 0)
    ("mantain" "maintain" nil 0)
    ("marraige" "marriage" nil 0)
    ("memeber" "member" nil 0)
    ("merchent" "merchant" nil 0)
    ("mesage" "message" nil 0)
    ("mesages" "messages" nil 0)
    ("mispell" "misspell" nil 0)
    ("mispelling" "misspelling" nil 0)
    ("mispellings" "misspellings" nil 0)
    ("mkae" "make" nil 0)
    ("mkaes" "makes" nil 0)
    ("mkaing" "making" nil 0)
    ("moeny" "money" nil 0)
    ("morgage" "mortgage" nil 0)
    ("mroe" "more" nil 0)
    ("mysefl" "myself" nil 0)
    ("myu" "my" nil 0)
    ("naive" "naive" nil 0)
    ("necassarily" "necessarily" nil 0)
    ("necassary" "necessary" nil 0)
    ("neccessarily" "necessarily" nil 0)
    ("neccessary" "necessary" nil 0)
    ("necesarily" "necessarily" nil 0)
    ("necesary" "necessary" nil 0)
    ("negotiaing" "negotiating" nil 0)
    ("nkow" "know" nil 0)
    ("nothign" "nothing" nil 0)
    ("nver" "never" nil 0)
    ("nwe" "new" nil 0)
    ("nwo" "now" nil 0)
    ("obediant" "obedient" nil 0)
    ("ocasion" "occasion" nil 0)
    ("occassion" "occasion" nil 0)
    ("occured" "occurred" nil 0)
    ("occurence" "occurrence" nil 0)
    ("occurences" "occurrences" nil 2)
    ("occurrance" "occurrence" nil 0)
    ("ocur" "occur" nil 0)
    ("odbc" "ODBC" nil 0)
    ("oeprator" "operator" nil 0)
    ("ofits" "of its" nil 0)
    ("ofthe" "of the" nil 0)
    ("oging" "going" nil 0)
    ("ohter" "other" nil 1)
    ("omre" "more" nil 1)
    ("oneof" "one of" nil 0)
    ("onepoint" "one point" nil 0)
    ("online" "on-line" nil 13)
    ("ont he" "on the" nil 0)
    ("onthe" "on the" nil 1)
    ("onyl" "only" nil 0)
    ("opcode" "op-code" nil 0)
    ("operaror" "operator" nil 0)
    ("oppasite" "opposite" nil 0)
    ("opperation" "operation" nil 0)
    ("oppertunity" "opportunity" nil 0)
    ("opposate" "opposite" nil 0)
    ("opposible" "opposable" nil 0)
    ("opposit" "opposite" nil 0)
    ("oppotunities" "opportunities" nil 0)
    ("oppotunity" "opportunity" nil 1)
    ("orginization" "organization" nil 0)
    ("orginized" "organized" nil 0)
    ("originial" "original" nil 0)
    ("orignal" "original" nil 0)
    ("otehr" "other" nil 0)
    ("otu" "out" nil 0)
    ("outof" "out of" nil 0)
    ("overthe" "over the" nil 0)
    ("ovverides" "overrides" nil 0)
    ("owrk" "work" nil 0)
    ("owuld" "would" nil 0)
    ("oxident" "oxidant" nil 0)
    ("papaer" "paper" nil 0)
    ("parliment" "parliament" nil 0)
    ("partof" "part of" nil 0)
    ("paticular" "particular" nil 0)
    ("paymetn" "payment" nil 0)
    ("paymetns" "payments" nil 0)
    ("pciture" "picture" nil 0)
    ("peice" "piece" nil 0)
    ("peices" "pieces" nil 0)
    ("peolpe" "people" nil 0)
    ("peopel" "people" nil 0)
    ("percentof" "percent of" nil 0)
    ("percentto" "percent to" nil 0)
    ("performence" "performance" nil 0)
    ("perhasp" "perhaps" nil 0)
    ("perhpas" "perhaps" nil 1)
    ("permanant" "permanent" nil 0)
    ("perminent" "permanent" nil 0)
    ("perscriptions" "prescriptions" nil 0)
    ("personalyl" "personally" nil 0)
    ("pleasent" "pleasant" nil 0)
    ("plugin" "plug-in" nil 0)
    ("poeple" "people" nil 0)
    ("porblem" "problem" nil 0)
    ("porblems" "problems" nil 0)
    ("porvide" "provide" nil 0)
    ("possable" "possible" nil 0)
    ("postition" "position" nil 0)
    ("potentialy" "potentially" nil 0)
    ("prefure" "prefer" nil 0)
    ("pregnent" "pregnant" nil 0)
    ("prelease" "release" nil 0)
    ("prerelease" "pre-release" nil 0)
    ("presance" "presence" nil 0)
    ("privleged" "privileged" nil 0)
    ("probelm" "problem" nil 0)
    ("probelms" "problems" nil 0)
    ("problesm" "problems" nil 0)
    ("proceding" "proceeding" nil 0)
    ("proctetion" "protection" nil 0)
    ("prominant" "prominent" nil 0)
    ("protction" "protection" nil 0)
    ("protoge" "protege" nil 0)
    ("psoition" "position" nil 0)
    ("ptogress" "progress" nil 0)
    ("puting" "putting" nil 0)
    ("pwoer" "power" nil 0)
    ("quater" "quarter" nil 0)
    ("quaters" "quarters" nil 0)
    ("quesion" "question" nil 0)
    ("quesions" "questions" nil 0)
    ("questioms" "questions" nil 0)
    ("questiosn" "questions" nil 0)
    ("questoin" "question" nil 0)
    ("quetion" "question" nil 0)
    ("quetions" "questions" nil 0)
    ("raidus" "RADIUS" nil 0)
    ("realyl" "really" nil 0)
    ("reccomend" "recommend" nil 0)
    ("reccommend" "recommend" nil 0)
    ("receieve" "receive" nil 0)
    ("recieve" "receive" nil 0)
    ("recieved" "received" nil 0)
    ("recieving" "receiving" nil 0)
    ("recomend" "recommend" nil 0)
    ("recomendation" "recommendation" nil 0)
    ("recomendations" "recommendations" nil 0)
    ("recomended" "recommended" nil 0)
    ("recomending" "recommending" nil 0)
    ("reconize" "recognize" nil 0)
    ("recrod" "record" nil 0)
    ("redirector" "re-director" nil 0)
    ("regardsless" "regardless" nil 0)
    ("regession" "regression" nil 0)
    ("regresion" "regression" nil 0)
    ("releated" "related" nil 0)
    ("religous" "religious" nil 0)
    ("relize" "realize" nil 0)
    ("reloacted" "relocated" nil 0)
    ("reltaed" "related" nil 0)
    ("reluctent" "reluctant" nil 0)
    ("remeber" "remember" nil 1)
    ("reommend" "recommend" nil 0)
    ("representativs" "representatives" nil 0)
    ("representives" "representatives" nil 0)
    ("represetned" "represented" nil 0)
    ("represnt" "represent" nil 0)
    ("requirment" "requirement" nil 1)
    ("requirments" "requirements" nil 0)
    ("reserach" "research" nil 1)
    ("resollution" "resolution" nil 0)
    ("resorces" "resources" nil 0)
    ("respomd" "respond" nil 0)
    ("respomse" "response" nil 0)
    ("responce" "response" nil 0)
    ("responsability" "responsibility" nil 0)
    ("responsable" "responsible" nil 0)
    ("responsibile" "responsible" nil 0)
    ("responsiblity" "responsibility" nil 0)
    ("restaraunt" "restaurant" nil 0)
    ("restuarant" "restaurant" nil 0)
    ("reult" "result" nil 0)
    ("reveiw" "review" nil 0)
    ("reveiwing" "reviewing" nil 0)
    ("rumers" "rumors" nil 0)
    ("runnning" "running" nil 0)
    ("rwite" "write" nil 0)
    ("rythm" "rhythm" nil 0)
    ("saidhe" "said he" nil 0)
    ("saidit" "said it" nil 0)
    ("saidthat" "said that" nil 0)
    ("saidthe" "said the" nil 0)
    ("scedule" "schedule" nil 0)
    ("sceduled" "scheduled" nil 0)
    ("scen" "scene" nil 0)
    ("scol" "scowl" nil 0)
    ("scoli" "scowl" nil 0)
    ("seance" "seance" nil 0)
    ("secratary" "secretary" nil 0)
    ("sectino" "section" nil 0)
    ("securtiy" "security" nil 0)
    ("seh" "she" nil 0)
    ("selectoin" "selection" nil 0)
    ("sentance" "sentence" nil 0)
    ("separeate" "separate" nil 0)
    ("seperate" "separate" nil 2)
    ("seperated" "separated" nil 0)
    ("sercumstances" "circumstances" nil 0)
    ("serveral" "several" nil 0)
    ("sez" "says" nil 0)
    ("shcool" "school" nil 0)
    ("shesaid" "she said" nil 0)
    ("shineing" "shining" nil 0)
    ("shiped" "shipped" nil 0)
    ("shoudl" "should" nil 0)
    ("shouldent" "shouldn't" nil 0)
    ("shouldnt" "shouldn't" nil 0)
    ("showinf" "showing" nil 0)
    ("signifacnt" "significant" nil 0)
    ("simalar" "similar" nil 0)
    ("similiar" "similar" nil 0)
    ("simpilified" "simplified" nil 0)
    ("simpyl" "simply" nil 0)
    ("sincerly" "sincerely" nil 0)
    ("sitll" "still" nil 0)
    ("smae" "same" nil 0)
    ("smoe" "some" nil 0)
    ("soem" "some" nil 0)
    ("sohw" "show" nil 0)
    ("soical" "social" nil 0)
    ("somethign" "something" nil 1)
    ("someting" "something" nil 0)
    ("somewaht" "somewhat" nil 0)
    ("somthing" "something" nil 0)
    ("somtimes" "sometimes" nil 0)
    ("soudn" "sound" nil 0)
    ("soudns" "sounds" nil 0)
    ("speach" "speech" nil 0)
    ("specificaly" "specifically" nil 0)
    ("specificalyl" "specifically" nil 0)
    ("statment" "statement" nil 0)
    ("statments" "statements" nil 0)
    ("stnad" "stand" nil 0)
    ("stopry" "story" nil 0)
    ("stoyr" "story" nil 0)
    ("stpo" "stop" nil 0)
    ("strentgh" "strength" nil 0)
    ("stroy" "story" nil 0)
    ("struggel" "struggle" nil 0)
    ("strugle" "struggle" nil 0)
    ("studnet" "student" nil 1)
    ("sublanguange" "sublanguage" nil 0)
    ("substitued" "substituted" nil 0)
    ("successfull" "successful" nil 0)
    ("successfuly" "successfully" nil 0)
    ("successfulyl" "successfully" nil 0)
    ("sucess" "success" nil 0)
    ("sucessfull" "successful" nil 0)
    ("sufficiant" "sufficient" nil 0)
    ("suposed" "supposed" nil 0)
    ("suppossed" "supposed" nil 0)
    ("suprise" "surprise" nil 0)
    ("suprised" "surprised" nil 1)
    ("suprisingly" "surprisingly" nil 0)
    ("swiming" "swimming" nil 0)
    ("tahn" "than" nil 0)
    ("taht" "that" nil 2)
    ("talekd" "talked" nil 0)
    ("talior" "tailor" nil 0)
    ("talkign" "talking" nil 0)
    ("tath" "that" nil 0)
    ("tecnical" "technical" nil 0)
    ("teh" "the" nil 8)
    ("tehy" "they" nil 0)
    ("terminiated" "terminated" nil 0)
    ("termoil" "turmoil" nil 0)
    ("tghe" "the" nil 0)
    ("tghis" "this" nil 0)
    ("thansk" "thanks" nil 0)
    ("thatthe" "that the" nil 0)
    ("thecompany" "the company" nil 0)
    ("thefirst" "the first" nil 0)
    ("thegovernment" "the government" nil 0)
    ("themself" "themselves" nil 0)
    ("themselfs" "themselves" nil 0)
    ("thenew" "the new" nil 0)
    ("theri" "their" nil 0)
    ("thesame" "the same" nil 0)
    ("thetwo" "the two" nil 0)
    ("theyll" "they'll" nil 0)
    ("theyve" "they've" nil 0)
    ("thgat" "that" nil 0)
    ("thge" "the" nil 0)
    ("thier" "their" nil 0)
    ("thigsn" "things" nil 0)
    ("thisyear" "this year" nil 0)
    ("thna" "than" nil 0)
    ("thne" "then" nil 0)
    ("thnig" "thing" nil 0)
    ("thnigs" "things" nil 0)
    ("threatend" "threatened" nil 0)
    ("thsi" "this" nil 0)
    ("thsoe" "those" nil 0)
    ("thta" "that" nil 0)
    ("tihs" "this" nil 0)
    ("timne" "time" nil 0)
    ("tiogether" "together" nil 0)
    ("tje" "the" nil 0)
    ("tjhe" "the" nil 0)
    ("tkae" "take" nil 1)
    ("tkaes" "takes" nil 0)
    ("tkaing" "taking" nil 0)
    ("tlaking" "talking" nil 0)
    ("todya" "today" nil 0)
    ("togehter" "together" nil 0)
    ("tomorow" "tomorrow" nil 0)
    ("tongiht" "tonight" nil 0)
    ("tonihgt" "tonight" nil 0)
    ("totaly" "totally" nil 0)
    ("totalyl" "totally" nil 0)
    ("tothe" "to the" nil 0)
    ("towrad" "toward" nil 0)
    ("traditionalyl" "traditionally" nil 0)
    ("transfered" "transferred" nil 0)
    ("truely" "truly" nil 0)
    ("truley" "truly" nil 0)
    ("tryed" "tried" nil 0)
    ("tthe" "the" nil 0)
    ("tyhat" "that" nil 0)
    ("tyhe" "the" nil 0)
    ("udnerstand" "understand" nil 0)
    ("understnad" "understand" nil 0)
    ("undert he" "under the" nil 0)
    ("unicode" "Unicode" nil 0)
    ("unitedstates" "United States" nil 0)
    ("unliek" "unlike" nil 0)
    ("unpleasently" "unpleasantly" nil 0)
    ("unregistared" "unregistered" nil 0)
    ("untill" "until" nil 1)
    ("untilll" "until" nil 0)
    ("useing" "using" nil 0)
    ("usualyl" "usually" nil 0)
    ("veyr" "very" nil 0)
    ("virtualyl" "virtually" nil 0)
    ("vrey" "very" nil 0)
    ("vulnerible" "vulnerable" nil 0)
    ("waht" "what" nil 3)
    ("warrent" "warrant" nil 0)
    ("wasnt" "wasn't" nil 0)
    ("watn" "want" nil 0)
    ("wehn" "when" nil 0)
    ("wernt" "weren't" nil 0)
    ("werre" "were" nil 0)
    ("wethee" "whether" nil 0)
    ("whcih" "which" nil 0)
    ("wherre" "where" nil 0)
    ("whic" "which" nil 1)
    ("whihc" "which" nil 0)
    ("whos" "who's" nil 0)
    ("whove" "who've" nil 0)
    ("whta" "what" nil 0)
    ("wief" "wife" nil 0)
    ("wierd" "weird" nil 0)
    ("wihch" "which" nil 0)
    ("wiht" "with" nil 0)
    ("willbe" "will be" nil 0)
    ("windoes" "windows" nil 0)
    ("witha" "with a" nil 3)
    ("withe" "with" nil 0)
    ("withthe" "with the" nil 1)
    ("wiull" "will" nil 0)
    ("wnat" "want" nil 0)
    ("wnated" "wanted" nil 0)
    ("wnats" "wants" nil 0)
    ("woh" "who" nil 0)
    ("wohle" "whole" nil 0)
    ("wokr" "work" nil 0)
    ("woudl" "would" nil 0)
    ("woudln" "wouldn" nil 0)
    ("wouldbe" "would be" nil 0)
    ("wouldnt" "wouldn't" nil 0)
    ("wriet" "write" nil 0)
    ("writting" "writing" nil 0)
    ("wrod" "word" nil 0)
    ("wroet" "wrote" nil 0)
    ("wroking" "working" nil 0)
    ("wtih" "with" nil 0)
    ("wuould" "would" nil 0)
    ("wya" "way" nil 0)
    ("yera" "year" nil 0)
    ("yeras" "years" nil 0)
    ("yersa" "years" nil 0)
    ("yoiu" "you" nil 0)
    ("youare" "you are" nil 0)
    ("youd" "you'd" nil 0)
    ("youre" "you're" nil 0)
    ("youve" "you've" nil 0)
    ("ytou" "you" nil 0)
    ("yuo" "you" nil 0)
    ("yuor" "your" nil 2)
   ))

(define-abbrev-table 'gnus-group-mode-abbrev-table '())

(define-abbrev-table 'grep-mode-abbrev-table '())

(define-abbrev-table 'gud-mode-abbrev-table '())

(define-abbrev-table 'helm-grep-mode-abbrev-table '())

(define-abbrev-table 'helm-major-mode-abbrev-table '())

(define-abbrev-table 'helm-moccur-mode-abbrev-table '())

(define-abbrev-table 'helm-occur-mode-abbrev-table '())

(define-abbrev-table 'help-mode-abbrev-table '())

(define-abbrev-table 'html-mode-abbrev-table '())

(define-abbrev-table 'ibuffer-mode-abbrev-table '())

(define-abbrev-table 'idl-mode-abbrev-table '())

(define-abbrev-table 'image-dired-display-image-mode-abbrev-table '())

(define-abbrev-table 'image-dired-thumbnail-mode-abbrev-table '())

(define-abbrev-table 'inferior-ess-julia-mode-abbrev-table '())

(define-abbrev-table 'inferior-ess-mode-abbrev-table '())

(define-abbrev-table 'inferior-ess-r-mode-abbrev-table '())

(define-abbrev-table 'inferior-ess-stata-mode-abbrev-table '())

(define-abbrev-table 'inferior-js-mode-abbrev-table '())

(define-abbrev-table 'inferior-julia-mode-abbrev-table '())

(define-abbrev-table 'inferior-python-mode-abbrev-table '())

(define-abbrev-table 'ivy-occur-grep-mode-abbrev-table '())

(define-abbrev-table 'ivy-occur-mode-abbrev-table '())

(define-abbrev-table 'java-mode-abbrev-table '())

(define-abbrev-table 'jdee-mode-abbrev-table
  '(
    ("catch" "catch" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ("finally" "finally" c-electric-continued-statement 0)
    ("while" "while" c-electric-continued-statement 0)
   ))

(define-abbrev-table 'jdee-run-mode-abbrev-table '())

(define-abbrev-table 'jdee-stacktrace-mode-abbrev-table '())

(define-abbrev-table 'js-jsx-mode-abbrev-table '())

(define-abbrev-table 'js-mode-abbrev-table '())

(define-abbrev-table 'julia-mode-abbrev-table '())

(define-abbrev-table 'latex-mode-abbrev-table '())

(define-abbrev-table 'lisp-mode-abbrev-table '())

(define-abbrev-table 'locate-mode-abbrev-table '())

(define-abbrev-table 'log-edit-mode-abbrev-table '())

(define-abbrev-table 'lua-mode-abbrev-table '())

(define-abbrev-table 'magit-cherry-mode-abbrev-table '())

(define-abbrev-table 'magit-diff-mode-abbrev-table '())

(define-abbrev-table 'magit-log-mode-abbrev-table '())

(define-abbrev-table 'magit-log-select-mode-abbrev-table '())

(define-abbrev-table 'magit-merge-preview-mode-abbrev-table '())

(define-abbrev-table 'magit-mode-abbrev-table '())

(define-abbrev-table 'magit-popup-mode-abbrev-table '())

(define-abbrev-table 'magit-process-mode-abbrev-table '())

(define-abbrev-table 'magit-reflog-mode-abbrev-table '())

(define-abbrev-table 'magit-refs-mode-abbrev-table '())

(define-abbrev-table 'magit-repolist-mode-abbrev-table '())

(define-abbrev-table 'magit-revision-mode-abbrev-table '())

(define-abbrev-table 'magit-section-mode-abbrev-table '())

(define-abbrev-table 'magit-stash-mode-abbrev-table '())

(define-abbrev-table 'magit-stashes-mode-abbrev-table '())

(define-abbrev-table 'magit-status-mode-abbrev-table '())

(define-abbrev-table 'magit-submodule-list-mode-abbrev-table '())

(define-abbrev-table 'markdown-mode-abbrev-table
  '(
    ("abjudicate" "adjudicate" nil 0)
    ("accessbility" "accessibility" nil 0)
    ("affecters" "affects" nil 0)
    ("aggreataion" "aggregating" nil 0)
    ("appliable" "applicable" nil 0)
    ("apporrioate" "appreciate" nil 0)
    ("apprcomiately" "approximately" nil 0)
    ("approcimately" "approximately" nil 0)
    ("approimiately" "approximately" nil 0)
    ("apprval" "approval" nil 0)
    ("apprxomiately" "approximately" nil 0)
    ("assciate" "associate" nil 0)
    ("asscociated" "associated" nil 0)
    ("assumpiton" "assumption" nil 0)
    ("avaiable" "available" nil 0)
    ("averange" "average" nil 0)
    ("avoibable" "avoidable" nil 0)
    ("bernullie" "Bernoulli" nil 0)
    ("caclulated" "calculated" nil 0)
    ("caculate" "calculate" nil 2)
    ("calcuate" "calculate" nil 0)
    ("calcuating" "calculating" nil 0)
    ("calculato" "calculator" nil 1)
    ("calulated" "calculated" nil 0)
    ("centeral" "central" nil 0)
    ("chracteristics" "characteristics" nil 0)
    ("coeffcient" "coefficient" nil 0)
    ("coefficent" "coefficient" nil 0)
    ("coefficiet" "coefficient" nil 0)
    ("coeffient" "coefficient" nil 0)
    ("coloradoran" "Coloradan" nil 0)
    ("complate" "complete" nil 0)
    ("conditing" "conducting" nil 0)
    ("consititues" "constitutes" nil 0)
    ("consuting" "consulting" nil 0)
    ("contigence" "contingency" nil 0)
    ("continous" "continuous" nil 0)
    ("convineous" "confines" nil 0)
    ("corelation" "correlation" nil 0)
    ("coutnies" "counties" nil 1)
    ("decrreases" "decreases" nil 0)
    ("decsition" "decision" nil 0)
    ("definiton" "Definition" nil 0)
    ("deivation" "deviation" nil 9)
    ("deiviation" "deviation" nil 5)
    ("deivition" "deviation" nil 14)
    ("depedent" "dependent" nil 0)
    ("desrib" "describe" nil 0)
    ("devaiation" "deviation" nil 0)
    ("devition" "deviation" nil 0)
    ("differet" "different" nil 0)
    ("disatisfied" "dissatisfied" nil 0)
    ("disbribution" "distribution" nil 0)
    ("disperson" "dispersion" nil 1)
    ("disribution" "distribution" nil 0)
    ("distibution" "distribution" nil 0)
    ("distribubted" "distributed" nil 0)
    ("distribued" "distributed" nil 0)
    ("distriubtions" "distributions" nil 0)
    ("distrubitions" "distributions" nil 0)
    ("distrubted" "distributed" nil 0)
    ("documention" "document ion" nil 0)
    ("effiency" "Efficiency" nil 0)
    ("elemement" "element" nil 0)
    ("equaliaty" "equality" nil 0)
    ("esimate" "estimate" nil 0)
    ("esimator" "estimator" nil 0)
    ("esmate" "estate" nil 0)
    ("estimatino" "estimation" nil 0)
    ("formatulate" "Formulate" nil 0)
    ("formulatino" "Formulation" nil 0)
    ("fractial" "Fractal" nil 1)
    ("frequence" "frequency" nil 0)
    ("fucntion" "function" nil 0)
    ("generatea" "generates" nil 1)
    ("generlize" "generalize" nil 0)
    ("geogrpahic" "Geographic" nil 0)
    ("heterogenous" "heterogeneous" nil 0)
    ("histigram" "histogram" nil 0)
    ("hypotesis" "hypothesis" nil 0)
    ("hypothethically" "Hypothetically" nil 0)
    ("indenpdent" "Independent" nil 0)
    ("indepdent" "independent" nil 0)
    ("independknt" "independent" nil 0)
    ("inequaliaty" "inequality" nil 0)
    ("inferrential" "inferential" nil 0)
    ("influend" "influenced" nil 0)
    ("inforation" "information" nil 0)
    ("inpretation" "Interpretation" nil 0)
    ("intepretation" "interpretation" nil 0)
    ("interchanble" "interchangeable" nil 0)
    ("internval" "internal" nil 1)
    ("interpreation" "Interpretation" nil 0)
    ("interpretion" "interpreting" nil 1)
    ("intersted" "interested" nil 0)
    ("inteval" "interval" nil 1)
    ("mannually" "manually" nil 1)
    ("mantatory" "mandatory" nil 0)
    ("metroplitan" "metropolitan" nil 0)
    ("mortatlity" "mortality" nil 0)
    ("mulitple" "Multiple" nil 0)
    ("nonparametric" "Non-parametric" nil 4)
    ("normaliaty" "normality" nil 0)
    ("normazlied" "normalized" nil 0)
    ("pausible" "plausible" nil 0)
    ("performace" "performance" nil 0)
    ("poission" "Poisson" nil 0)
    ("poluation" "pollution" nil 4)
    ("polulation" "population" nil 0)
    ("popluation" "population" nil 3)
    ("popoulation" "population" nil 3)
    ("populaiton" "population" nil 0)
    ("populatino" "population" nil 0)
    ("porportation" "perpetuation" nil 0)
    ("positivie" "positive" nil 0)
    ("postive" "positive" nil 4)
    ("postively" "positively" nil 0)
    ("postivie" "Positive" nil 0)
    ("preferrable" "Preferable" nil 0)
    ("presential" "presidential" nil 2)
    ("probabiltiy" "probability" nil 0)
    ("probablity" "probability" nil 16)
    ("proceduure" "Procedure" nil 0)
    ("prohibiited" "prohibited" nil 0)
    ("qeustion" "question" nil 0)
    ("questionaiers" "questionnaires" nil 0)
    ("questionairs" "questioners" nil 1)
    ("quoeta" "Quota" nil 0)
    ("randonly" "randomly" nil 0)
    ("reachs" "reach's" nil 0)
    ("regargless" "regardless" nil 0)
    ("relatinoship" "relationship" nil 0)
    ("representitive" "Representative" nil 0)
    ("reseachers" "researchers" nil 0)
    ("saptial" "Spatial" nil 0)
    ("servey" "survey" nil 0)
    ("sigfnicance" "significance" nil 0)
    ("signficance" "significance" nil 1)
    ("signifance" "significance" nil 0)
    ("signifances" "significance's" nil 0)
    ("signifcance" "significance" nil 0)
    ("simiarly" "Similarly" nil 0)
    ("situlation" "situation" nil 0)
    ("situlations" "situations" nil 0)
    ("specifly" "specify" nil 0)
    ("standardlization" "standardization" nil 0)
    ("standarlized" "standardized" nil 0)
    ("statitical" "statistical" nil 0)
    ("statitics" "Statistics" nil 1)
    ("stes" "Steps" nil 0)
    ("straighforward" "straightforward" nil 0)
    ("straightford" "straight ford" nil 0)
    ("straightline" "straight line" nil 0)
    ("stribution" "attribution" nil 0)
    ("substitiuted" "substituted" nil 0)
    ("supppose" "Suppose" nil 0)
    ("surved" "served" nil 0)
    ("symetrical" "symmetrical" nil 0)
    ("symetry" "symmetry" nil 0)
    ("sympotoms" "symptoms" nil 0)
    ("temerpat" "temperate" nil 0)
    ("tempearature" "temperature" nil 0)
    ("tendence" "tendency" nil 0)
    ("varabiles" "variables" nil 0)
    ("variace" "variance" nil 0)
    ("varible" "variable" nil 0)
    ("varitions" "variations" nil 0)
    ("visulizations" "visualizations" nil 0)
    ("wiouth" "with" nil 0)
    ("xcolor" "color" nil 0)
   ))

(define-abbrev-table 'markdown-view-mode-abbrev-table '())

(define-abbrev-table 'matlab-mode-abbrev-table '())

(define-abbrev-table 'matlab-shell-help-mode-abbrev-table '())

(define-abbrev-table 'matlab-shell-topic-mode-abbrev-table '())

(define-abbrev-table 'message-mode-abbrev-table '())

(define-abbrev-table 'messages-buffer-mode-abbrev-table '())

(define-abbrev-table 'mhtml-mode-abbrev-table '())

(define-abbrev-table 'neotree-mode-abbrev-table '())

(define-abbrev-table 'notmuch-hello-mode-abbrev-table '())

(define-abbrev-table 'notmuch-message-mode-abbrev-table '())

(define-abbrev-table 'notmuch-search-mode-abbrev-table '())

(define-abbrev-table 'notmuch-show-mode-abbrev-table '())

(define-abbrev-table 'notmuch-tree-mode-abbrev-table '())

(define-abbrev-table 'nxml-mode-abbrev-table '())

(define-abbrev-table 'objc-mode-abbrev-table '())

(define-abbrev-table 'occur-edit-mode-abbrev-table '())

(define-abbrev-table 'occur-mode-abbrev-table '())

(define-abbrev-table 'octave-abbrev-table '())

(define-abbrev-table 'org-export-stack-mode-abbrev-table '())

(define-abbrev-table 'org-journal-mode-abbrev-table
  '(
    ("chlorphyll" "chlorophyll" nil 0)
    ("clamined" "claimed" nil 0)
    ("estiate" "estimate" nil 0)
    ("fluorescenes" "fluorescence" nil 0)
    ("genrated" "generated" nil 0)
    ("illustraiton" "illustration" nil 0)
    ("intereesting" "interesting" nil 0)
    ("medidate" "meditate" nil 0)
    ("meterologyical" "meteorological" nil 0)
    ("obselete" "obsolete" nil 0)
    ("protocal" "protocol" nil 0)
    ("virtural" "virtual" nil 0)
    ("wedensday" "Wednesday" nil 0)
   ))

(define-abbrev-table 'org-journal-search-mode-abbrev-table '())

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("accessbility" "accessibility" nil 0)
    ("accruacy" "accuracy" nil 0)
    ("accuately" "accurately" nil 0)
    ("acquistion" "acquisition" nil 0)
    ("adressing" "addressing" nil 0)
    ("advatnage" "advantage" nil 0)
    ("aeras" "areas" nil 0)
    ("alghouth" "Although" nil 1)
    ("altorithm" "algorithm" nil 1)
    ("analalyze" "analyze" nil 0)
    ("analsyis" "analysis" nil 0)
    ("anayze" "analyze" nil 0)
    ("appraoch" "approach" nil 0)
    ("apprently" "apparently" nil 0)
    ("approproiate" "appropriate" nil 0)
    ("apprproriate" "appropriate" nil 0)
    ("arbitary" "arbitrary" nil 2)
    ("assumptioons" "assumptions" nil 0)
    ("atmsphere" "atmosphere" nil 0)
    ("attendence" "attendance" nil 1)
    ("authorative" "authoritative" nil 2)
    ("autocoreelation" "correlation" nil 0)
    ("avaiable" "available" nil 7)
    ("avaiablity" "availability" nil 0)
    ("avaialability" "availability" nil 0)
    ("avaialable" "available" nil 2)
    ("avaialbiliaty" "availability" nil 0)
    ("backgound" "background" nil 0)
    ("baised" "biased" nil 0)
    ("basicaly" "Basically" nil 0)
    ("behavvior" "behavior" nil 0)
    ("borned" "borne" nil 0)
    ("brigheness" "brightness" nil 0)
    ("brighness" "brightness" nil 1)
    ("bueray" "Bureau" nil 0)
    ("calcuation" "calculation" nil 0)
    ("capitalizaing" "capitalize" nil 0)
    ("capution" "caption" nil 0)
    ("certaily" "certainly" nil 0)
    ("certaintly" "certainly" nil 0)
    ("chacteristics" "characteristics" nil 0)
    ("charactierics" "characterizes" nil 0)
    ("charactize" "characterize" nil 0)
    ("chater" "chapter" nil 0)
    ("chracteristics" "characteristics" nil 0)
    ("classifer" "classifier" nil 1)
    ("classifers" "classifiers" nil 0)
    ("cliame" "climate" nil 0)
    ("clutral" "cultural" nil 0)
    ("coeffcients" "coefficients" nil 0)
    ("collquium" "Colloquium" nil 0)
    ("commerical" "commercial" nil 0)
    ("commericial" "commercial" nil 0)
    ("commmunities" "communities" nil 0)
    ("commnication" "communication" nil 0)
    ("commounity" "community" nil 0)
    ("commucation" "commutation" nil 0)
    ("commuinities" "communities" nil 0)
    ("commuities" "communities" nil 0)
    ("communites" "communities" nil 0)
    ("communiticating" "communicating" nil 0)
    ("communties" "communities" nil 0)
    ("compareing" "comparing" nil 0)
    ("comparision" "comparison" nil 3)
    ("comparitive" "Comparative" nil 1)
    ("compliement" "complement" nil 0)
    ("comprehensenvie" "comprehensive" nil 0)
    ("comprehnsive" "comprehensive" nil 0)
    ("comprensive" "comprehensive" nil 0)
    ("comprhensive" "comprehensive" nil 0)
    ("comptationally" "computationally" nil 0)
    ("comuting" "co muting" nil 0)
    ("concepturally" "conceptually" nil 0)
    ("concusion" "concussion" nil 0)
    ("confoudning" "confounding" nil 0)
    ("conidtional" "conditional" nil 0)
    ("consistenly" "consistently" nil 0)
    ("constituition" "Constitution" nil 0)
    ("conterparts" "counterparts" nil 0)
    ("conventinal" "conventional" nil 0)
    ("convicing" "con vicing" nil 1)
    ("coronaviurs" "Coronaries" nil 0)
    ("covariances" "covariance" nil 7)
    ("crisises" "crisis es" nil 0)
    ("critized" "criticized" nil 0)
    ("darkota" "Dakota" nil 0)
    ("deficienceis" "deficiencies" nil 0)
    ("definitiveness" "definiteness" nil 0)
    ("delinateion" "delineation" nil 0)
    ("delination" "delineation" nil 0)
    ("deliveables" "deliverable" nil 0)
    ("deliverables" "Deliverable" nil 9)
    ("demographyic" "demographic" nil 0)
    ("depsite" "Despite" nil 0)
    ("descade" "decade" nil 0)
    ("determistic" "deterministic" nil 0)
    ("deveices" "devices" nil 0)
    ("diaster" "duster" nil 7)
    ("dicussion" "discussion" nil 0)
    ("dicussions" "discussions" nil 0)
    ("dieases" "disease" nil 0)
    ("diffreent" "different" nil 0)
    ("dimentions" "dimensions" nil 0)
    ("dirctor" "Director" nil 0)
    ("disadvanges" "disadvantages" nil 0)
    ("disaggerated" "desegregated" nil 2)
    ("discuovery" "discovery" nil 0)
    ("displinary" "disciplinary" nil 0)
    ("disseminatio" "dissemination" nil 0)
    ("distribtion" "distribution" nil 0)
    ("distrition" "distortion" nil 0)
    ("disucssion" "Discussion" nil 4)
    ("disucssions" "discussions" nil 1)
    ("disussions" "discussions" nil 0)
    ("dyamics" "dynamics" nil 1)
    ("dynamcics" "dynamics" nil 1)
    ("dynamcis" "dynamics" nil 0)
    ("dynmiacs" "dynamics" nil 0)
    ("dynmics" "dynamics" nil 0)
    ("effictiveness" "Effectiveness" nil 0)
    ("elabotrated" "elaborated" nil 0)
    ("emgerging" "emerging" nil 0)
    ("envirionment" "environment" nil 0)
    ("enviroment" "environment" nil 0)
    ("environental" "environmental" nil 0)
    ("epedemilogical" "epidemiological" nil 0)
    ("epidemogical" "epidemiological" nil 0)
    ("epidemoligcal" "epidemiological" nil 0)
    ("epidemotical" "epidemiological" nil 0)
    ("equaivalent" "equivalent" nil 0)
    ("establised" "established" nil 0)
    ("everytime" "every time" nil 0)
    ("evideces" "evidences" nil 0)
    ("examplary" "exemplary" nil 0)
    ("excutables" "executable" nil 0)
    ("excute" "execute" nil 2)
    ("exibhibited" "exhibited" nil 0)
    ("eximaine" "examine" nil 0)
    ("existint" "Exist int" nil 0)
    ("expereiences" "experiences" nil 0)
    ("experteise" "expertise" nil 0)
    ("explaination" "explanations" nil 0)
    ("explanart" "explanatory" nil 0)
    ("explanary" "explanatory" nil 0)
    ("exploreing" "exploring" nil 1)
    ("expoential" "exponential" nil 0)
    ("extentive" "extensive" nil 0)
    ("extraodinary" "extraordinary" nil 0)
    ("flexiblity" "flexibility" nil 1)
    ("followinw" "following" nil 0)
    ("foucs" "focus" nil 3)
    ("geo" "Geo" nil 0)
    ("geographiees" "geographies" nil 0)
    ("geosaptial" "geospatial" nil 1)
    ("geospatial" "Geospatial" nil 8)
    ("granularities" "granularity's" nil 0)
    ("gurrantee" "guarantee" nil 0)
    ("hehaviors" "behaviors" nil 0)
    ("heterogeneities" "heterogeneity's" nil 3)
    ("heterogenity" "heterogeneity" nil 0)
    ("heterogneity" "heterogeneity" nil 0)
    ("heterogneous" "heterogeneous" nil 0)
    ("hightlights" "highlights" nil 0)
    ("hoever" "However" nil 0)
    ("https" "HTTP" nil 0)
    ("illustation" "illustration" nil 0)
    ("imporvments" "improvements" nil 0)
    ("imposssible" "impossible" nil 0)
    ("incoporate" "incorporate" nil 2)
    ("incoproated" "Incorporated" nil 0)
    ("incorpoted" "Incorporated" nil 0)
    ("indidual" "individual" nil 0)
    ("individiual" "individual" nil 0)
    ("indivildual" "individual" nil 0)
    ("indterdisplinary" "interdisciplinary" nil 0)
    ("inegrate" "integrate" nil 0)
    ("infectiours" "infectious" nil 0)
    ("inferrential" "Inferential" nil 0)
    ("inforamtion" "information" nil 0)
    ("informaiton" "information" nil 0)
    ("infromation" "information" nil 0)
    ("inherment" "inherent" nil 0)
    ("inidicate" "indicate" nil 0)
    ("intellitence" "intelligence" nil 0)
    ("intereestig" "interesting" nil 0)
    ("intergrating" "integrating" nil 0)
    ("interlectural" "Intellectual" nil 0)
    ("intermidiate" "intermediate" nil 2)
    ("interpretor" "interpreter" nil 0)
    ("intersting" "inter sting" nil 0)
    ("intestigate" "investigate" nil 0)
    ("intesting" "in testing" nil 0)
    ("intial" "initial" nil 1)
    ("intrest" "interest" nil 0)
    ("investitation" "investigation" nil 0)
    ("kish" "Knish" nil 0)
    ("licences" "licenses" nil 0)
    ("lighning" "Lightning" nil 0)
    ("literautre" "Literature" nil 0)
    ("lockdown" "lock down" nil 0)
    ("logstics" "Logistics" nil 0)
    ("makie" "make" nil 0)
    ("mandataory" "Mandatory" nil 0)
    ("materails" "materials" nil 1)
    ("mathemtical" "mathematical" nil 0)
    ("measureable" "measurable" nil 0)
    ("mecahnistic" "Mechanistic" nil 0)
    ("mechanisom" "mechanism" nil 0)
    ("mechanmism" "mechanism" nil 2)
    ("mehtods" "methods" nil 0)
    ("microsofot" "Microsoft" nil 0)
    ("misintepretation" "misinterpretation" nil 0)
    ("mitigateion" "mitigation" nil 0)
    ("mobi" "mo bi" nil 1)
    ("mobil" "mil" nil 0)
    ("moblility" "mobility" nil 0)
    ("morden" "modern" nil 0)
    ("mortaility" "mortality" nil 0)
    ("nightitme" "Nighttime" nil 0)
    ("nomrality" "normality" nil 0)
    ("nonparametric" "non-parametric" nil 0)
    ("nortiorislly" "notoriously" nil 0)
    ("numerours" "numerous" nil 0)
    ("observrations" "observations" nil 0)
    ("ontarior" "Ontario" nil 0)
    ("openaddresses" "Open Addresses" nil 0)
    ("ot" "OT" nil 5)
    ("overaching" "overarching" nil 0)
    ("overally" "overall" nil 0)
    ("paragraphy" "paragraph" nil 0)
    ("paremters" "parameters" nil 0)
    ("pariticuarly" "Piratically" nil 0)
    ("particuarly" "particularly" nil 9)
    ("partipate" "participate" nil 0)
    ("paticuarly" "particularly" nil 0)
    ("peneration" "penetration" nil 1)
    ("percpetion" "perception" nil 0)
    ("performnance" "performance" nil 0)
    ("peronsla" "Prensa" nil 0)
    ("phyiscal" "physical" nil 1)
    ("phyisical" "physical" nil 0)
    ("poential" "potential" nil 0)
    ("poluation" "pollution" nil 0)
    ("postive" "positive" nil 0)
    ("potenial" "potential" nil 0)
    ("potentential" "penitential" nil 0)
    ("potentiral" "potential" nil 2)
    ("poulation" "population" nil 0)
    ("preimilary" "Premolar" nil 0)
    ("probablity" "Probability" nil 0)
    ("projrect" "project" nil 0)
    ("pubulished" "published" nil 0)
    ("purto" "Puerto" nil 0)
    ("quantiative" "quantitative" nil 0)
    ("quantitiative" "quantitative" nil 0)
    ("quantitiatively" "quantitatively" nil 0)
    ("rahter" "rater" nil 0)
    ("reflectnace" "reflectance" nil 0)
    ("regularted" "regulated" nil 1)
    ("reliabilities" "reliability" nil 0)
    ("represenging" "representing" nil 0)
    ("representitative" "Representative" nil 1)
    ("reseearch" "research" nil 1)
    ("resillence" "resilience" nil 0)
    ("resillices" "resolves" nil 0)
    ("resillience" "resilience" nil 2)
    ("resilliences" "resilience" nil 0)
    ("resillient" "resilient" nil 0)
    ("resoluton" "resolution" nil 1)
    ("sallelite" "satellite" nil 0)
    ("satelight" "sate light" nil 0)
    ("satelite" "satellite" nil 0)
    ("satellige" "Satellite" nil 0)
    ("satistics" "statistics" nil 0)
    ("satllite" "satellite" nil 0)
    ("satuation" "situation" nil 4)
    ("sciece" "science" nil 0)
    ("scientifc" "scientific" nil 0)
    ("sensensing" "sen sensing" nil 0)
    ("senstive" "sensitive" nil 0)
    ("seperately" "separately" nil 0)
    ("sesning" "sensing" nil 0)
    ("sicence" "science" nil 0)
    ("sigifnicant" "significant" nil 0)
    ("siginificant" "significant" nil 0)
    ("siginificantly" "significantly" nil 0)
    ("similarliy" "Similarly" nil 0)
    ("simpfilied" "simplified" nil 0)
    ("socialogist" "sociologist" nil 0)
    ("socioecnomic" "socioeconomic" nil 0)
    ("socioeconocmi" "socioeconomic" nil 0)
    ("sournces" "sources" nil 0)
    ("spatiotempora" "spatiotemporal" nil 0)
    ("speccifically" "Specifically" nil 0)
    ("spectural" "spectral" nil 2)
    ("specturm" "spectrum" nil 0)
    ("speptacular" "spectacular" nil 0)
    ("spetacular" "spectacular" nil 0)
    ("sphosticaed" "sophisticate" nil 0)
    ("sphosticated" "sophisticated" nil 0)
    ("statitsical" "Statistical" nil 0)
    ("strenght" "strength" nil 0)
    ("stu" "Stu" nil 0)
    ("studey" "study" nil 0)
    ("successues" "successes" nil 0)
    ("surffer" "suffer" nil 0)
    ("survy" "Survey" nil 0)
    ("sustaianbility" "sustainability" nil 0)
    ("systemetically" "systematically" nil 0)
    ("taclking" "tackling" nil 0)
    ("techlogy" "technology" nil 0)
    ("technlogy" "technology" nil 0)
    ("technoligically" "Technologically" nil 0)
    ("technologoy" "technology" nil 0)
    ("technoloigies" "technologies" nil 0)
    ("technoloy" "technology" nil 0)
    ("techonogy" "technology" nil 0)
    ("theatre" "theater" nil 0)
    ("trainigng" "training" nil 0)
    ("trajectoris" "trajectories" nil 0)
    ("transimission" "transmission" nil 0)
    ("transision" "transition" nil 0)
    ("transparancy" "transparency" nil 0)
    ("trendmendous" "tremendous" nil 0)
    ("trianing" "training" nil 0)
    ("trvivial" "trivial" nil 0)
    ("ubiquitious" "ubiquitous" nil 0)
    ("uncertainy" "Uncertainly" nil 0)
    ("underdanding" "understanding" nil 0)
    ("understaindg" "understand" nil 0)
    ("understanidng" "understanding" nil 0)
    ("undertanding" "understanding" nil 1)
    ("univerity" "University" nil 0)
    ("unprecendented" "unprecedented" nil 1)
    ("unprecendeted" "unprecedented" nil 0)
    ("unprecendted" "unprecedented" nil 0)
    ("valeus" "values" nil 0)
    ("varibility" "variability" nil 0)
    ("varible" "variable" nil 0)
    ("varibles" "variables" nil 1)
    ("varius" "various" nil 0)
    ("youthmappers" "Youth Mappers" nil 0)
   ))

(define-abbrev-table 'outline-mode-abbrev-table '())

(define-abbrev-table 'package-menu-mode-abbrev-table '())

(define-abbrev-table 'pandoc-@-mode-abbrev-table '())

(define-abbrev-table 'pdf-annot-list-mode-abbrev-table '())

(define-abbrev-table 'pdf-occur-buffer-mode-abbrev-table '())

(define-abbrev-table 'pdf-outline-buffer-mode-abbrev-table '())

(define-abbrev-table 'pike-mode-abbrev-table '())

(define-abbrev-table 'plain-tex-mode-abbrev-table '())

(define-abbrev-table 'poly-fallback-mode-abbrev-table '())

(define-abbrev-table 'poly-head-tail-mode-abbrev-table '())

(define-abbrev-table 'process-menu-mode-abbrev-table '())

(define-abbrev-table 'prog-mode-abbrev-table '())

(define-abbrev-table 'python-mode-abbrev-table '())

(define-abbrev-table 'python-mode-skeleton-abbrev-table
  '(
   ))

(define-abbrev-table 'restclient-mode-abbrev-table '())

(define-abbrev-table 'sas-dir-mode-abbrev-table '())

(define-abbrev-table 'scss-mode-abbrev-table '())

(define-abbrev-table 'select-tags-table-mode-abbrev-table '())

(define-abbrev-table 'sgml-mode-abbrev-table '())

(define-abbrev-table 'sh-mode-abbrev-table '())

(define-abbrev-table 'shell-mode-abbrev-table '())

(define-abbrev-table 'slitex-mode-abbrev-table '())

(define-abbrev-table 'smime-mode-abbrev-table '())

(define-abbrev-table 'snippet-mode-abbrev-table '())

(define-abbrev-table 'special-mode-abbrev-table '())

(define-abbrev-table 'speedbar-mode-abbrev-table '())

(define-abbrev-table 'sql-mode-abbrev-table '())

(define-abbrev-table 'srecode-template-mode-abbrev-table '())

(define-abbrev-table 'tablist-mode-abbrev-table '())

(define-abbrev-table 'tabulated-list-mode-abbrev-table '())

(define-abbrev-table 'term-mode-abbrev-table '())

(define-abbrev-table 'tex-mode-abbrev-table '())

(define-abbrev-table 'tex-shell-abbrev-table '())

(define-abbrev-table 'text-mode-abbrev-table '())

(define-abbrev-table 'url-cookie-mode-abbrev-table '())

(define-abbrev-table 'use-package-statistics-mode-abbrev-table '())

(define-abbrev-table 'vc-git-log-edit-mode-abbrev-table '())

(define-abbrev-table 'vc-git-log-view-mode-abbrev-table '())

(define-abbrev-table 'vc-git-region-history-mode-abbrev-table '())

(define-abbrev-table 'web-mode-abbrev-table '())

(define-abbrev-table 'woman-mode-abbrev-table '())

(define-abbrev-table 'xref--xref-buffer-mode-abbrev-table '())

(define-abbrev-table 'yaml-mode-abbrev-table '())

(define-abbrev-table 'ycmd-fixit-mode-abbrev-table '())

(define-abbrev-table 'ycmd-view-mode-abbrev-table '())

