local VimMode = hs.loadSpoon('VimMode')
local vim = VimMode:new()

hs.hotkey.bind({'ctrl'}, ';', function()
  vim:enter()
end)

vim:enterWithSequence('jk')
vim:disableForApp('iTerm2')
vim:disableForApp('MacVim')
vim:disableForApp('Terminal')
vim:disableForApp('VIM')
vim:disableForApp('Vivaldi')
vim:disableForApp('Firefox')
vim:disableForApp('Emacs')
