set nocompatible              " be iMproved, required
filetype off                  " required
set mouse=a
set relativenumber
set number

"""""""""""""""""""""""""""""""""""""""""""""""""""""
"""   Plug
""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Install vim-plug if we don't already have it
if empty(glob("~/.vim/autoload/plug.vim"))
    "" Ensure all needed directories exist  (Thanks @kapadiamush)
    silent execute "!mkdir -p ~/.vim/plugged"
    silent execute "!mkdir -p ~/.vim/autoload"
    " Download the actual plugin manager
    execute "!curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim"
endif

call plug#begin('~/.vim/plugged')
Plug 'github/copilot.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-abolish'
"Plug 'reedes/vim-pencil'
"let g:pencil#textwidth = 75
"Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-scripts/Solarized'
Plug 'arcticicestudio/nord-vim'
Plug 'cocopon/iceberg.vim'
Plug 'morhetz/gruvbox'
Plug 'ervandew/supertab'
let g:SuperTabDefaultCompletionType = '<C-n>'
let g:SuperTabCrMapping = 0
let g:SuperTabClosePreviewOnPopupClose = 1

Plug 'jalvesaq/Nvim-R', {'for': ['r']}
Plug 'SirVer/ultisnips', {'for': ['r','py', 'tex']}
Plug 'honza/vim-snippets', {'for': ['r','py', 'tex']}
let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<tab>'
let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

"Plug 'vim-scripts/LanguageTool', {'for': ['tex', 'markdown', 'text']}
"Plug 'rhysd/vim-grammarous', {'for': ['tex', 'markdown', 'text']}
"
"Plug 'vim-syntastic/syntastic', {'for': ['tex', 'markdown', 'text']}
"let g:syntastic_mode_map = { 'mode': 'passive'}
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_tex_checkers = ["lacheck", "proselint", "text/"language_check"]
"let g:syntastic_text_checkers = ["proselint", "language_check"]
"let g:syntastic_text_language_check_args = "--language=en-US  --"disable=MORFOLOGIK_RULE_EN_US" 

Plug 'junegunn/limelight.vim'
let g:limelight_conceal_ctermfg = 'black'
let g:limelight_default_coefficient = 0.9
Plug 'surfcao/vim-autocorrect', {'for': ['tex', 'markdown', 'text']}
Plug 'jalvesaq/Nvim-R', {'for': 'r'}
Plug 'lervag/vimtex', {'for': 'tex'}
Plug 'rickhowe/diffchar.vim'
"let g:vimtex_latexmk_continuous=1
let g:vimtex_complete_bib = { 'simple': 1 }
let g:vimtex_format_enabled=1
let g:vimtex_syntax_conceal_disable=1 
let g:vimtex_compiler_latexmk = {'out_dir' : 'output', 'callback' : 0}
if has('mac') == 0
	let g:vimtex_view_method='zathura' 
else
	let g:vimtex_view_method='skim' 
	"let g:vimtex_view_method='sioyek' 
        "let g:vimtex_view_sioyek_exe = '/Applications/sioyek.app/Contents/MacOS/sioyek'
endif 

"Plug 'Konfekt/vim-sentence-chopper'
Plug 'vim-pandoc/vim-pandoc', {'for': ['markdown', 'pandoc']}
" put pandoc using hard wrapping, default is soft wrapping
let g:pandoc#formatting#mode = "h"
let g:pandoc#formatting#textwidth=75
let g:pandoc#modules#disabled = ["folding"]
let g:pandoc#command#latex_engine = 'pdflatex'
let g:pandoc#keyboard#enabled_submodules = ["lists", "references", "sections", "links"]
"let g:pandoc#filetypes#handled = ['pandoc', 'markdown']
Plug 'vim-pandoc/vim-pandoc-syntax', {'for': ['markdown', 'pandoc']}
let g:pandoc#syntax#conceal#blacklist=['subscript']
call plug#end()
filetype plugin indent on                   " required!
syntax on

"""""""""""""""""""""""""""""""""""""""""""""""""""""
""   General settings
""""""""""""""""""""""""""""""""""""""""""""""""""""""

" path to search files
"set path+=$HOME/GDrive/bib/
"set path+=$HOME/Git/lab/papers/**
set path+=$HOME/Git/hub/papers/**
set path+=$HOME/Git/hub/proposals/**
set wildignore+=**/.git/**,*.aux,*.blg,*.dvi,*.log,*.out,*.fls,*.fdb_latexmk
set wildignore+=*.swp,*.bak
set wildignore+=*.tar.*
set wildignorecase
set wildmenu
"set wildmode=list:full
set wildmode=list:longest,list:full
set showcmd


" put the backup, swp and undo file into the same place
set backupdir=$HOME/.vim/.backup//,/tmp
set directory=$HOME/.vim/.swp//,/tmp
if exists('+undodir')
    set undodir=$HOME/.vim/.undo//,/tmp
    set undofile
endif

set ignorecase
set smartcase
set hlsearch
set tabstop=8
set shiftwidth=8
set keywordprg=:help

set tw=75
" not automatically reformatting, soft wrap
set formatoptions-=t
set formatoptions+=j
"autocmd FileType tex,markdown set formatoptions+=a
set wrapmargin=0

"map fm {v}!par -w75<CR> vmap fm !par -w75<CR>
set formatprg=par\ -w75
set incsearch
set wrap
set linebreak
set breakindent

"for macvim
set backspace=indent,eol,start


set spell spelllang=en_us
set spellfile=$HOME/Dropbox/vim/spell/en.utf-8.add
hi SpellBad ctermbg=22
set spell
" Under latex, this is a workaround only works for non-comments
autocmd FileType tex syntax spell toplevel
" syntax spell toplevel
set dictionary+=/usr/share/dict/words
set thesaurus+=$HOME/Dropbox/vim/thesaurus/mthesaur.txt
" not search included file for completion
set complete-=i
set complete+=kspell

" Ctrl-l automatically fix the typos
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

set autowriteall

set history=1000
set undolevels=1000
set title "change the terminal's title
set showmatch
set hidden
set noruler "hide the status line
"set nonumber " No line numbering
set display=lastline
set nojoinspaces " no extra spaces when joining

"""""""""""""""""""""""""""""""""""""""""""""""""""""
""   Key Mappings
""""""""""""""""""""""""""""""""""""""""""""""""""""""
" some shortcuts
let mapleader = "\<Space>"
let maplocalleader = ","
nmap <Leader>q :nohlsearch<CR>
nnoremap <Leader>w :w<CR>
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
"nmap <Leader>q :nohlsearch<CR>
" buffer switch
nnoremap <LocalLeader>b :ls<CR>
nnoremap <LocalLeader>p :bp<CR>
nnoremap <LocalLeader>n :bn<CR>
nnoremap <LocalLeader>d :bd<CR>
nnoremap <LocalLeader><tab> :e#<CR>
nnoremap <LocalLeader>1 :1b<CR>
nnoremap <LocalLeader>2 :2b<CR>
nnoremap <LocalLeader>3 :3b<CR>
nnoremap <LocalLeader>4 :4b<CR>
nnoremap <LocalLeader>5 :5b<CR>
nnoremap <LocalLeader>6 :6b<CR>
nnoremap <LocalLeader>7 :7b<CR>
nnoremap <LocalLeader>8 :8b<CR>
nnoremap <LocalLeader>9 :9b<CR>
nnoremap <LocalLeader>0 :10b<CR>

" Window 
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <Leader>o <C-w>o

" Hardwrap, softwrap
"map j gj
"map k gk
" support line jump with softwrap source: https://stackoverflow.com/questions/20975928/moving-the-cursor-through-long-soft-wrapped-lines-in-vim
noremap <expr> j v:count ? 'j' : 'gj'
noremap <expr> k v:count ? 'k' : 'gk'

" Make Y consistent with D
nnoremap Y y$
" Visually select the text that are recently edited
nmap gV `[v`]

" Use Q for formatting the current paragraph (or selection)
vnoremap Q gw
nnoremap Q gwap

" One sentence per line. source:
" https://vi.stackexchange.com/questions/2846/how-to-set-up-vim-to-work-with-one-sentence-per-line
"
function! SentenceChopper() range
	silent execute a:firstline.','.a:lastline.'s/[.!?]\zs /\r/g'
endfunction 
"set formatexpr=SentenceChopper(v:lnum,v:lnum+v:count-1)
vmap <Leader>s :call SentenceChopper() <CR>
nmap <Leader>s vap :call SentenceChopper() <CR>

" The vanilla c-u and c-w will are undoable, the following map add them to
" the undolist, so it can be undo by 'u'
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

"""""""""""""""""""""""""""""""
"""  Solarized color theme  
"""""""""""""""""""""""""""""""
set background=dark 
"set background=light 
set t_Co=256
" option name default optional
"let g:solarized_termcolors= 256
"if &t_Co<256 && !has('gui_running')
"	let g:solarized_termcolors= 16
"endif
let g:solarized_termtrans = 1 | 0
let g:solarized_degrade = 0 | 0
let g:solarized_bold = 1 | 0 
let g:solarized_underline = 1 | 0
"Most terminals (including screen) don't handle italics right, but urxvt
"can. 
let g:solarized_italic = 1 | 0 
let g:solarized_contrast = "high"| "normal" or "low" 
let g:solarized_visibility= "high"| "normal" or "low"
"colorscheme solarized
"colorscheme nord
colorscheme iceberg
"colorscheme gruvbox
highlight LineNr ctermbg=NONE
highlight Normal ctermbg=NONE 

"""""""""""""""""""
"""   Markdown  
"""""""""""""""""""

" Auto detect filetype
autocmd BufRead,BufNewFile *.md,*.markdown set filetype=markdown.pandoc
autocmd BufRead,BufNewFile *.txt,*.text setfiletype=text
autocmd BufRead,BufNewFile *.tex setfiletype=tex.text
 
"""""""""""""""""""
"""    Latex    
"""""""""""""""""""
let g:tex_flavor = "latex"

"autocmd FileType tex setlocal iskeyword+=:,-

"inoremap { {}<ESC>i
"inoremap [ []<ESC>i
"inoremap ( ()<ESC>i

" make going to a line number easier.
"nnoremap <CR> G

"""""""""""""""""""
"""    R       
"""""""""""""""""""
" R script settings
"let maplocalleader = ","
"vmap r <Plug>RDSendSelection
"nmap r <Plug>RDSendLine
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
"let R_vsplit=1

""""""""""""""""""""""
"""" Language Check 
""""""""""""""""""""""
"let g:languagetool_jar='$HOME/mytools/LanguageTool-3.7/languagetool-commandline.jar'
"disable the rule of 'possible spelling mistake'
"let g:languagetool_disable_rules='MORFOLOGIK_RULE_EN_US'

""""""""""""""""""""""
"""" netrw 
""""""""""""""""""""""

" Tweaks for browsing using netrw
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=2  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_winsize = 25     " 25 percent of width
"let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

""""""""""""""""""""""""""
"""   My commands 
""""""""""""""""""""""""""
" write a file with root 
cmap w!! w !sudo tee % >/dev/null
" Create the `tags` file (may need to install ctags first)
command! MakeTags !ctags -R . &&pushd $HOME/OneDrive/bib && ctags library.bib &&popd

" add the tags to the path
set tags+=$HOME/OneDrive/bib/tags

" change cursor types in insert mode
"
autocmd InsertEnter,InsertLeave * set cul!

"let &t_SI = "\e[6 q"
"let &t_EI = "\e[2 q"

" source: https://stackoverflow.com/questions/6488683/how-to-change-the-cursor-between-normal-and-insert-modes-in-vim/42118416#42118416
" https://vi.stackexchange.com/questions/19748/vimenter-autocmd-to-change-cursor-shape-sometimes-outputs-escape-sequences

" Set up vertical vs block cursor for insert/normal mode
if &term =~ "screen.*"
    let &t_ti.="\eP\e[1 q\e\\"
    let &t_SI.="\eP\e[6 q\e\\"
    let &t_EI.="\eP\e[2 q\e\\"
    let &t_te.="\eP\e[0 q\e\\"
else
    let &t_ti.="\<Esc>[1 q"
    let &t_SI.="\<Esc>[6 q"
    let &t_EI.="\<Esc>[2 q"
    let &t_te.="\<Esc>[0 q"
endif

"" Optionally reset the cursor on start:
"augroup myCmds
"au!
""autocmd VimEnter * silent !echo -ne "\e[2 q"
"autocmd VimEnter * startinsert | stopinsert
"augroup END

set ttimeoutlen=0

" enable italic
"let &t_ZH="\e[3m"
"let &t_ZR="\e[23m"
